framework:
    html_sanitizer:
        sanitizers:
            app.video_sanitizer:
                allow_elements:
                    iframe: ['src', 'width', 'height', 'title', 'allow', 'allowfullscreen', 'frameborder', 'style', 'class']
                    div: ['class', 'style']
                allow_safe_elements: true
