framework:
    rate_limiter:
        registration:
            policy: fixed_window
            limit: 10
            interval: '15 minutes'
        
        api:
            policy: token_bucket
            limit: 100
            rate: { interval: '1 minute', amount: 10 }
