twig:
  default_path: "%kernel.project_dir%/templates"
  form_themes: ["bootstrap_5_layout.html.twig"]

  paths:
    # Email css
    "%kernel.project_dir%/assets/styles": styles
    # Images css
    "%kernel.project_dir%/assets/images": images

  globals:
    # the value is the service's id
    app_notification: '@App\Repository\NotificationRepository'
    premium_access: '%env(bool:PREMIUM_ACCESS)%'
    app_name: '%env(APP_NAME)%'
    app_short_name: '%env(APP_SHORT_NAME)%'
    app_company: '%env(APP_COMPANY)%'
    app_url: '%env(APP_URL)%'

when@test:
  twig:
    strict_variables: true
