---
# Production environment override
services:
  php:
    build:
      context: .
      target: frankenphp_prod
    environment:
      APP_ENV: prod
      SERVER_NAME: "http://academie.lerocher.fr"
      APP_SECRET: ${APP_SECRET}
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      TRUSTED_PROXIES: "*"
      MAILER_DSN: ${SYMFONY_MAILER_DSN}
      MAILER_DSN_IMPORTANT: ${SYMFONY_MAILER_DSN_IMPORTANT}
      BREVO_API_KEY: ${SYMFONY_BREVO_API_KEY}
      BREVO_LIST_ID:
      BREVO_FROM_EMAIL:
      DEFAULT_FROM_EMAIL:
