<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260317235447 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE activity (id INT AUTO_INCREMENT NOT NULL, action VARCHAR(255) NOT NULL, target_name VARCHAR(255) DEFAULT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at DATETIME DEFAULT NULL, user_id INT NOT NULL, INDEX IDX_AC74095AA76ED395 (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE amaevent (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, date DATETIME NOT NULL, guest_id INT NOT NULL, INDEX IDX_AD26732C9A4AA658 (guest_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE answer (id INT AUTO_INCREMENT NOT NULL, content LONGTEXT NOT NULL, votes INT NOT NULL, question_id INT NOT NULL, author_id INT NOT NULL, INDEX IDX_DADD4A251E27F6BF (question_id), INDEX IDX_DADD4A25F675F31B (author_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE assignment (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, rubric JSON DEFAULT NULL, lesson_id INT NOT NULL, rubric_entity_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_30C544BACDF80196 (lesson_id), UNIQUE INDEX UNIQ_30C544BA654329D5 (rubric_entity_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE assignment_submission (id INT AUTO_INCREMENT NOT NULL, content LONGTEXT NOT NULL, status VARCHAR(255) NOT NULL, file_path VARCHAR(500) DEFAULT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at DATETIME DEFAULT NULL, assignment_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_E5A63E2CD19302F8 (assignment_id), INDEX IDX_E5A63E2CA76ED395 (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE avatar_frame (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, identifier VARCHAR(255) NOT NULL, css_class VARCHAR(255) NOT NULL, image_path VARCHAR(255) DEFAULT NULL, level_required INT DEFAULT 0 NOT NULL, UNIQUE INDEX UNIQ_A46B93FA772E836A (identifier), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE badge (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, image VARCHAR(255) DEFAULT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at DATETIME DEFAULT NULL, badge_type_id INT NOT NULL, INDEX IDX_FEF0481DC3C8852F (badge_type_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE badge_user (badge_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_299D3A50F7A2C2FC (badge_id), INDEX IDX_299D3A50A76ED395 (user_id), PRIMARY KEY (badge_id, user_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE badge_type (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, image VARCHAR(255) DEFAULT NULL, code VARCHAR(20) NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE behind_the_scenes (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, content LONGTEXT NOT NULL, min_xp_required INT NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE bonus (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, file_path VARCHAR(500) NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE calendar (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, url VARCHAR(255) DEFAULT NULL, embed LONGTEXT DEFAULT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE chat_message (id INT AUTO_INCREMENT NOT NULL, content LONGTEXT NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at DATETIME DEFAULT NULL, author_id INT NOT NULL, cohort_id INT NOT NULL, INDEX IDX_FAB3FC16F675F31B (author_id), INDEX IDX_FAB3FC1635983C93 (cohort_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE code_review (id INT AUTO_INCREMENT NOT NULL, comment LONGTEXT NOT NULL, rating INT NOT NULL, submission_id INT NOT NULL, reviewer_id INT NOT NULL, INDEX IDX_6C5D964E1FD4933 (submission_id), INDEX IDX_6C5D96470574616 (reviewer_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE cohort (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, image VARCHAR(255) DEFAULT NULL, year SMALLINT NOT NULL, status VARCHAR(255) DEFAULT \'draft\' NOT NULL, start_at DATETIME DEFAULT NULL, invitation_token VARCHAR(64) DEFAULT NULL, brand_color VARCHAR(7) DEFAULT NULL, logo_path VARCHAR(255) DEFAULT NULL, discord_webhook_url VARCHAR(500) DEFAULT NULL, slack_webhook_url VARCHAR(500) DEFAULT NULL, is_vip TINYINT DEFAULT 0 NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at DATETIME DEFAULT NULL, slug VARCHAR(255) NOT NULL, calendar_id INT DEFAULT NULL, conversation_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_D3B8C16B33FC351A (invitation_token), INDEX IDX_D3B8C16BA40A2C8 (calendar_id), UNIQUE INDEX UNIQ_D3B8C16B9AC0396 (conversation_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE cohort_course (cohort_id INT NOT NULL, course_id INT NOT NULL, INDEX IDX_A8FE089635983C93 (cohort_id), INDEX IDX_A8FE0896591CC992 (course_id), PRIMARY KEY (cohort_id, course_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE cohort_challenge (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, target_value INT NOT NULL, start_date DATETIME NOT NULL, end_date DATETIME NOT NULL, cohort_id INT NOT NULL, INDEX IDX_8316140A35983C93 (cohort_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE collaborative_note (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, url VARCHAR(255) NOT NULL, cohort_id INT NOT NULL, INDEX IDX_1A99550035983C93 (cohort_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE comment (id INT AUTO_INCREMENT NOT NULL, content LONGTEXT NOT NULL, timestamp INT DEFAULT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at DATETIME DEFAULT NULL, parent_id INT DEFAULT NULL, user_id INT NOT NULL, notification_id INT DEFAULT NULL, lesson_id INT DEFAULT NULL, INDEX IDX_9474526C727ACA70 (parent_id), INDEX IDX_9474526CA76ED395 (user_id), INDEX IDX_9474526CEF1A9D84 (notification_id), INDEX IDX_9474526CCDF80196 (lesson_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE comment_user (comment_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_ABA574A5F8697D13 (comment_id), INDEX IDX_ABA574A5A76ED395 (user_id), PRIMARY KEY (comment_id, user_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE completion (id INT AUTO_INCREMENT NOT NULL, completed TINYINT DEFAULT NULL, needs_review TINYINT DEFAULT 0 NOT NULL, score DOUBLE PRECISION DEFAULT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at DATETIME DEFAULT NULL, lesson_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_38D6377ECDF80196 (lesson_id), INDEX IDX_38D6377EA76ED395 (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE conversation (id INT AUTO_INCREMENT NOT NULL, is_private TINYINT DEFAULT 0 NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE conversation_user (conversation_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_5AECB5559AC0396 (conversation_id), INDEX IDX_5AECB555A76ED395 (user_id), PRIMARY KEY (conversation_id, user_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE cosmetic (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(50) NOT NULL, price INT NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE course (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, image VARCHAR(255) DEFAULT NULL, slug VARCHAR(255) NOT NULL, status VARCHAR(20) DEFAULT NULL, visibility VARCHAR(255) DEFAULT \'public\' NOT NULL, item_order SMALLINT DEFAULT NULL, revenue_share_percentage SMALLINT DEFAULT 0 NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at DATETIME DEFAULT NULL, author_id INT NOT NULL, INDEX IDX_169E6FB9F675F31B (author_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE course_user (course_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_45310B4F591CC992 (course_id), INDEX IDX_45310B4FA76ED395 (user_id), PRIMARY KEY (course_id, user_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE course_completion (id INT AUTO_INCREMENT NOT NULL, completed TINYINT DEFAULT NULL, certificate_type VARCHAR(20) DEFAULT \'simple\' NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at DATETIME DEFAULT NULL, course_id INT DEFAULT NULL, user_id INT DEFAULT NULL, INDEX IDX_E73479FD591CC992 (course_id), INDEX IDX_E73479FDA76ED395 (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE daily_win (id INT AUTO_INCREMENT NOT NULL, summary LONGTEXT NOT NULL, date DATETIME NOT NULL, user_id INT NOT NULL, INDEX IDX_B2F8DD1AA76ED395 (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE dashboard_widget (id INT AUTO_INCREMENT NOT NULL, type VARCHAR(50) NOT NULL, position INT NOT NULL, user_id INT NOT NULL, INDEX IDX_6AC217EBA76ED395 (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE equity (id INT AUTO_INCREMENT NOT NULL, points INT NOT NULL, reason VARCHAR(255) DEFAULT NULL, user_id INT NOT NULL, INDEX IDX_5424235EA76ED395 (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE evaluation (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, score DOUBLE PRECISION NOT NULL, max_score DOUBLE PRECISION NOT NULL, feedback LONGTEXT DEFAULT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at DATETIME DEFAULT NULL, user_id INT NOT NULL, cohort_id INT DEFAULT NULL, INDEX IDX_1323A575A76ED395 (user_id), INDEX IDX_1323A57535983C93 (cohort_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE event (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, start_at DATETIME NOT NULL, end_at DATETIME DEFAULT NULL, location VARCHAR(255) DEFAULT NULL, type_id INT DEFAULT NULL, calendar_id INT DEFAULT NULL, cohort_id INT DEFAULT NULL, INDEX IDX_3BAE0AA7C54C8C93 (type_id), INDEX IDX_3BAE0AA7A40A2C8 (calendar_id), INDEX IDX_3BAE0AA735983C93 (cohort_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE event_category (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE external_account (id INT AUTO_INCREMENT NOT NULL, platform VARCHAR(50) NOT NULL, account_id VARCHAR(255) NOT NULL, user_id INT NOT NULL, INDEX IDX_A4948FE7A76ED395 (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE external_learning (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, type VARCHAR(50) NOT NULL, status VARCHAR(50) NOT NULL, user_id INT NOT NULL, INDEX IDX_20091631A76ED395 (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE flashcard (id INT AUTO_INCREMENT NOT NULL, question LONGTEXT NOT NULL, answer LONGTEXT NOT NULL, deck_id INT NOT NULL, INDEX IDX_70511A09111948DC (deck_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE flashcard_deck (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, owner_id INT NOT NULL, INDEX IDX_627CAED77E3C61F9 (owner_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE glossary_term (id INT AUTO_INCREMENT NOT NULL, term VARCHAR(255) NOT NULL, definition LONGTEXT NOT NULL, is_approved TINYINT DEFAULT 0 NOT NULL, UNIQUE INDEX UNIQ_334345DDA50FE78D (term), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE hackathon (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, start_date DATETIME NOT NULL, end_date DATETIME NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE hackathon_user (hackathon_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_58930177996D90CF (hackathon_id), INDEX IDX_58930177A76ED395 (user_id), PRIMARY KEY (hackathon_id, user_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE helpful_vote (id INT AUTO_INCREMENT NOT NULL, voter_id INT NOT NULL, comment_id INT NOT NULL, INDEX IDX_59855A3BEBB4B8AD (voter_id), INDEX IDX_59855A3BF8697D13 (comment_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE job_offer (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, company VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, url VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE lesson (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, content LONGTEXT DEFAULT NULL, slug VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, video_embeded LONGTEXT DEFAULT NULL, video_url VARCHAR(255) DEFAULT NULL, status VARCHAR(20) DEFAULT NULL, duration INT DEFAULT NULL, item_order SMALLINT DEFAULT NULL, audio_path VARCHAR(255) DEFAULT NULL, audio_duration INT DEFAULT NULL, embeddings JSON DEFAULT NULL, transcript LONGTEXT DEFAULT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at DATETIME DEFAULT NULL, module_id INT NOT NULL, author_id INT DEFAULT NULL, INDEX IDX_F87474F3AFC2B591 (module_id), INDEX IDX_F87474F3F675F31B (author_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE lesson_tip (id INT AUTO_INCREMENT NOT NULL, content LONGTEXT NOT NULL, lesson_id INT NOT NULL, author_id INT NOT NULL, INDEX IDX_3AF61EAFCDF80196 (lesson_id), INDEX IDX_3AF61EAFF675F31B (author_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE mentorship (id INT AUTO_INCREMENT NOT NULL, status VARCHAR(50) NOT NULL, mentor_id INT NOT NULL, mentee_id INT NOT NULL, INDEX IDX_ADE55FF4DB403044 (mentor_id), INDEX IDX_ADE55FF45C3E47C3 (mentee_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE message (id INT AUTO_INCREMENT NOT NULL, content LONGTEXT NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at DATETIME DEFAULT NULL, conversation_id INT NOT NULL, sender_id INT NOT NULL, INDEX IDX_B6BD307F9AC0396 (conversation_id), INDEX IDX_B6BD307FF624B39D (sender_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE mind_map (id INT AUTO_INCREMENT NOT NULL, data JSON NOT NULL, module_id INT NOT NULL, UNIQUE INDEX UNIQ_912CB0CFAFC2B591 (module_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE module (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, slug VARCHAR(255) NOT NULL, status VARCHAR(20) DEFAULT NULL, item_order SMALLINT DEFAULT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at DATETIME DEFAULT NULL, author_id INT DEFAULT NULL, INDEX IDX_C242628F675F31B (author_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE module_course (module_id INT NOT NULL, course_id INT NOT NULL, INDEX IDX_BC9D2F96AFC2B591 (module_id), INDEX IDX_BC9D2F96591CC992 (course_id), PRIMARY KEY (module_id, course_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE module_completion (id INT AUTO_INCREMENT NOT NULL, completed TINYINT DEFAULT NULL, score DOUBLE PRECISION DEFAULT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at DATETIME DEFAULT NULL, module_id INT NOT NULL, user_id INT DEFAULT NULL, INDEX IDX_AD331CE3AFC2B591 (module_id), INDEX IDX_AD331CE3A76ED395 (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE note (id INT AUTO_INCREMENT NOT NULL, content LONGTEXT NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at DATETIME DEFAULT NULL, user_id INT NOT NULL, lesson_id INT NOT NULL, INDEX IDX_CFBDFA14A76ED395 (user_id), INDEX IDX_CFBDFA14CDF80196 (lesson_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE note_likes (note_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_2CDAEDAA26ED0855 (note_id), INDEX IDX_2CDAEDAAA76ED395 (user_id), PRIMARY KEY (note_id, user_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE note_note_tag (note_id INT NOT NULL, note_tag_id INT NOT NULL, INDEX IDX_63214BFD26ED0855 (note_id), INDEX IDX_63214BFDA20034C5 (note_tag_id), PRIMARY KEY (note_id, note_tag_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE note_tag (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(50) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE notification (id INT AUTO_INCREMENT NOT NULL, message LONGTEXT NOT NULL, title VARCHAR(255) DEFAULT NULL, sent_at DATETIME DEFAULT NULL, send_at DATETIME DEFAULT NULL, is_read TINYINT DEFAULT NULL, link VARCHAR(500) DEFAULT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at DATETIME DEFAULT NULL, user_id INT DEFAULT NULL, INDEX IDX_BF5476CAA76ED395 (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE page (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(100) NOT NULL, content LONGTEXT NOT NULL, slug VARCHAR(100) NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE payment_setting (id INT AUTO_INCREMENT NOT NULL, rib VARCHAR(255) DEFAULT NULL, check_order VARCHAR(255) DEFAULT NULL, reception_address LONGTEXT DEFAULT NULL, note LONGTEXT DEFAULT NULL, pricing SMALLINT NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE payout (id INT AUTO_INCREMENT NOT NULL, amount INT NOT NULL, currency VARCHAR(3) NOT NULL, period_start DATE NOT NULL, period_end DATE NOT NULL, status VARCHAR(50) NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at DATETIME DEFAULT NULL, creator_id INT NOT NULL, course_id INT NOT NULL, INDEX IDX_4E2EA90261220EA6 (creator_id), INDEX IDX_4E2EA902591CC992 (course_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE peer_resource (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, url VARCHAR(255) NOT NULL, status VARCHAR(20) NOT NULL, author_id INT NOT NULL, INDEX IDX_A216EB19F675F31B (author_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE peer_review (id INT AUTO_INCREMENT NOT NULL, score SMALLINT NOT NULL, feedback LONGTEXT DEFAULT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at DATETIME DEFAULT NULL, submission_id INT NOT NULL, reviewer_id INT NOT NULL, INDEX IDX_47F6C716E1FD4933 (submission_id), INDEX IDX_47F6C71670574616 (reviewer_id), UNIQUE INDEX unique_peer_review (submission_id, reviewer_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE peer_review_score (id INT AUTO_INCREMENT NOT NULL, score SMALLINT NOT NULL, criterion_id INT NOT NULL, peer_review_id INT NOT NULL, INDEX IDX_E0C3DCBE97766307 (criterion_id), INDEX IDX_E0C3DCBEAE8F0C15 (peer_review_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE playlist (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, owner_id INT NOT NULL, INDEX IDX_D782112D7E3C61F9 (owner_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE playlist_lesson (playlist_id INT NOT NULL, lesson_id INT NOT NULL, INDEX IDX_170278C06BBD148 (playlist_id), INDEX IDX_170278C0CDF80196 (lesson_id), PRIMARY KEY (playlist_id, lesson_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE pomodoro_room (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, conversation_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_376385129AC0396 (conversation_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE portfolio_project (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, url VARCHAR(255) DEFAULT NULL, user_id INT NOT NULL, INDEX IDX_7906FF20A76ED395 (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE proof_of_work (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, link VARCHAR(255) NOT NULL, verification_hash VARCHAR(64) NOT NULL, user_id INT NOT NULL, UNIQUE INDEX UNIQ_56543EE74E8C91BF (verification_hash), INDEX IDX_56543EE7A76ED395 (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE push_subscription (id INT AUTO_INCREMENT NOT NULL, endpoint LONGTEXT NOT NULL, `keys` JSON NOT NULL, user_id INT NOT NULL, INDEX IDX_562830F3A76ED395 (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE question (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, content LONGTEXT NOT NULL, author_id INT NOT NULL, INDEX IDX_B6F7494EF675F31B (author_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE quiz (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at DATETIME DEFAULT NULL, lesson_id INT DEFAULT NULL, module_id INT DEFAULT NULL, INDEX IDX_A412FA92CDF80196 (lesson_id), INDEX IDX_A412FA92AFC2B591 (module_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE quiz_option (id INT AUTO_INCREMENT NOT NULL, text LONGTEXT NOT NULL, is_correct TINYINT NOT NULL, question_id INT NOT NULL, INDEX IDX_B7C2F0E91E27F6BF (question_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE quiz_question (id INT AUTO_INCREMENT NOT NULL, text LONGTEXT NOT NULL, quiz_id INT NOT NULL, INDEX IDX_6033B00B853CD175 (quiz_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE raffle_entry (id INT AUTO_INCREMENT NOT NULL, raffle_date DATETIME NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at DATETIME DEFAULT NULL, user_id INT NOT NULL, INDEX IDX_9F6F1A1CA76ED395 (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE referral (id INT AUTO_INCREMENT NOT NULL, is_completed TINYINT DEFAULT 0 NOT NULL, referrer_id INT NOT NULL, referee_id INT NOT NULL, INDEX IDX_73079D00798C22DB (referrer_id), UNIQUE INDEX UNIQ_73079D004A087CA2 (referee_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE reset_password_request (id INT AUTO_INCREMENT NOT NULL, selector VARCHAR(20) NOT NULL, hashed_token VARCHAR(100) NOT NULL, requested_at DATETIME NOT NULL, expires_at DATETIME NOT NULL, user_id INT NOT NULL, INDEX IDX_7CE748AA76ED395 (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE review (id INT AUTO_INCREMENT NOT NULL, comment LONGTEXT NOT NULL, rating SMALLINT NOT NULL, author_id INT NOT NULL, course_id INT NOT NULL, INDEX IDX_794381C6F675F31B (author_id), INDEX IDX_794381C6591CC992 (course_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE rubric (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE rubric_criterion (id INT AUTO_INCREMENT NOT NULL, label VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, max_points SMALLINT NOT NULL, rubric_id INT NOT NULL, INDEX IDX_98E476F9A29EC0FC (rubric_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE setting (id INT AUTO_INCREMENT NOT NULL, brevo_list_onboarded VARCHAR(255) DEFAULT NULL, brevo_list_alumni VARCHAR(255) DEFAULT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE shared_resource (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, url VARCHAR(255) NOT NULL, author_id INT NOT NULL, INDEX IDX_E9B50535F675F31B (author_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE site_setting (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, value LONGTEXT DEFAULT NULL, description LONGTEXT DEFAULT NULL, UNIQUE INDEX UNIQ_64D05A535E237E06 (name), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE skill (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE skill_user (skill_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_CAD24AFB5585C142 (skill_id), INDEX IDX_CAD24AFBA76ED395 (user_id), PRIMARY KEY (skill_id, user_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE skill_course (skill_id INT NOT NULL, course_id INT NOT NULL, INDEX IDX_39D43BAD5585C142 (skill_id), INDEX IDX_39D43BAD591CC992 (course_id), PRIMARY KEY (skill_id, course_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE skill_endorsement (id INT AUTO_INCREMENT NOT NULL, giver_id INT NOT NULL, receiver_id INT NOT NULL, skill_id INT NOT NULL, INDEX IDX_BFA5D76F75BD1D29 (giver_id), INDEX IDX_BFA5D76FCD53EDB6 (receiver_id), INDEX IDX_BFA5D76F5585C142 (skill_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE skill_node (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, xp_required INT NOT NULL, tree_id INT NOT NULL, prerequisite_id INT DEFAULT NULL, INDEX IDX_C23E74F778B64A2 (tree_id), INDEX IDX_C23E74F7276AF86B (prerequisite_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE skill_tree (id INT AUTO_INCREMENT NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE study_buddy_request (id INT AUTO_INCREMENT NOT NULL, status VARCHAR(20) NOT NULL, sender_id INT NOT NULL, recipient_id INT NOT NULL, INDEX IDX_2331E0ADF624B39D (sender_id), INDEX IDX_2331E0ADE92F8F78 (recipient_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE study_group (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, topic VARCHAR(255) NOT NULL, max_members INT DEFAULT 10 NOT NULL, creator_id INT NOT NULL, INDEX IDX_32BA142561220EA6 (creator_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE study_group_user (study_group_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_2355E9595DDDCCCE (study_group_id), INDEX IDX_2355E959A76ED395 (user_id), PRIMARY KEY (study_group_id, user_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE study_session_invite (id INT AUTO_INCREMENT NOT NULL, invite_token VARCHAR(64) NOT NULL, is_accepted TINYINT DEFAULT 0 NOT NULL, sender_id INT NOT NULL, UNIQUE INDEX UNIQ_72595DE45242FFC4 (invite_token), INDEX IDX_72595DE4F624B39D (sender_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE subtitle (id INT AUTO_INCREMENT NOT NULL, language VARCHAR(5) NOT NULL, content LONGTEXT NOT NULL, lesson_id INT NOT NULL, INDEX IDX_518597B1CDF80196 (lesson_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE team (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, company VARCHAR(255) NOT NULL, completed_lessons INT DEFAULT 0 NOT NULL, owner_id INT NOT NULL, cohort_id INT DEFAULT NULL, INDEX IDX_C4E0A61F7E3C61F9 (owner_id), INDEX IDX_C4E0A61F35983C93 (cohort_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE team_user (team_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_5C722232296CD8AE (team_id), INDEX IDX_5C722232A76ED395 (user_id), PRIMARY KEY (team_id, user_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE theme (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_9775E70877153098 (code), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE topic (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, category_id INT DEFAULT NULL, INDEX IDX_9D40DE1B12469DE2 (category_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE topic_category (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, restricted_to_cohort_id INT DEFAULT NULL, INDEX IDX_F07D94C7CF89DA37 (restricted_to_cohort_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE topic_vote (id INT AUTO_INCREMENT NOT NULL, topic_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_62FBE4D11F55203D (topic_id), INDEX IDX_62FBE4D1A76ED395 (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE transaction (id INT AUTO_INCREMENT NOT NULL, stripe_payment_id VARCHAR(255) NOT NULL, amount INT NOT NULL, currency VARCHAR(3) NOT NULL, status VARCHAR(50) NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at DATETIME DEFAULT NULL, user_id INT NOT NULL, INDEX IDX_723705D1A76ED395 (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE trivia_question (id INT AUTO_INCREMENT NOT NULL, question LONGTEXT NOT NULL, options JSON NOT NULL, correct_answer VARCHAR(1) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE `user` (id INT AUTO_INCREMENT NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, is_verified TINYINT NOT NULL, firstname VARCHAR(255) DEFAULT NULL, lastname VARCHAR(255) DEFAULT NULL, fullname VARCHAR(255) NOT NULL, last_connection_at DATETIME DEFAULT NULL, username VARCHAR(255) NOT NULL, image VARCHAR(255) DEFAULT NULL, bio LONGTEXT DEFAULT NULL, learning_manifesto LONGTEXT DEFAULT NULL, birth_date DATETIME DEFAULT NULL, address VARCHAR(100) DEFAULT NULL, score SMALLINT DEFAULT NULL, xp INT DEFAULT 0 NOT NULL, streak INT DEFAULT 0 NOT NULL, tier VARCHAR(100) DEFAULT \'Bronze\' NOT NULL, last_streak_date DATETIME DEFAULT NULL, timezone VARCHAR(50) DEFAULT \'UTC\' NOT NULL, payment_status VARCHAR(255) DEFAULT \'unpaid\' NOT NULL, google_authenticator_secret VARCHAR(255) DEFAULT NULL, stripe_customer_id VARCHAR(255) DEFAULT NULL, subscription_id VARCHAR(255) DEFAULT NULL, subscription_status VARCHAR(50) DEFAULT NULL, subscription_plan VARCHAR(50) DEFAULT NULL, jwt_secret VARCHAR(255) DEFAULT NULL, google_id VARCHAR(255) DEFAULT NULL, cover_photo VARCHAR(255) DEFAULT NULL, linkedin_id VARCHAR(255) DEFAULT NULL, website_url VARCHAR(255) DEFAULT NULL, github_url VARCHAR(255) DEFAULT NULL, is_profile_public TINYINT DEFAULT 0 NOT NULL, confetti_color VARCHAR(7) DEFAULT \'#000000\' NOT NULL, custom_goal VARCHAR(255) DEFAULT NULL, rss_feed_url VARCHAR(255) DEFAULT NULL, theme VARCHAR(20) DEFAULT \'light\' NOT NULL, login_token VARCHAR(128) DEFAULT NULL, login_token_expires_at DATETIME DEFAULT NULL, email_notifications TINYINT DEFAULT 1 NOT NULL, push_notifications TINYINT DEFAULT 1 NOT NULL, lesson_reminders TINYINT DEFAULT 1 NOT NULL, weekly_summary TINYINT DEFAULT 0 NOT NULL, weekly_goal_hours INT DEFAULT 0 NOT NULL, is_bootcamp_mode TINYINT DEFAULT 0 NOT NULL, is_alumni TINYINT DEFAULT 0 NOT NULL, quiz_combo INT DEFAULT 0 NOT NULL, rocher_coins INT DEFAULT 0 NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at DATETIME DEFAULT NULL, current_cohort_id INT DEFAULT NULL, team_id INT DEFAULT NULL, active_frame_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_8D93D649E7927C74 (email), UNIQUE INDEX UNIQ_8D93D649F85E0677 (username), UNIQUE INDEX UNIQ_8D93D649594766AF (login_token), INDEX IDX_8D93D649EEBE8D3F (current_cohort_id), INDEX IDX_8D93D649296CD8AE (team_id), INDEX IDX_8D93D649C52FB298 (active_frame_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE user_cohort (user_id INT NOT NULL, cohort_id INT NOT NULL, INDEX IDX_B6EADA56A76ED395 (user_id), INDEX IDX_B6EADA5635983C93 (cohort_id), PRIMARY KEY (user_id, cohort_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE user_unlocked_bonuses (user_id INT NOT NULL, bonus_id INT NOT NULL, INDEX IDX_9A506AA0A76ED395 (user_id), INDEX IDX_9A506AA069545666 (bonus_id), PRIMARY KEY (user_id, bonus_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE user_unlocked_frames (user_id INT NOT NULL, avatar_frame_id INT NOT NULL, INDEX IDX_414895E9A76ED395 (user_id), INDEX IDX_414895E95E1E529B (avatar_frame_id), PRIMARY KEY (user_id, avatar_frame_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE vip_event (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, date DATETIME NOT NULL, min_rank INT NOT NULL, cohort_id INT NOT NULL, INDEX IDX_462882D235983C93 (cohort_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE xp_transaction (id INT AUTO_INCREMENT NOT NULL, amount INT NOT NULL, reason VARCHAR(255) DEFAULT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at DATETIME DEFAULT NULL, user_id INT NOT NULL, INDEX IDX_E526D970A76ED395 (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT AUTO_INCREMENT NOT NULL, body LONGTEXT NOT NULL, headers LONGTEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL, available_at DATETIME NOT NULL, delivered_at DATETIME DEFAULT NULL, INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 (queue_name, available_at, delivered_at, id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE activity ADD CONSTRAINT FK_AC74095AA76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE amaevent ADD CONSTRAINT FK_AD26732C9A4AA658 FOREIGN KEY (guest_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE answer ADD CONSTRAINT FK_DADD4A251E27F6BF FOREIGN KEY (question_id) REFERENCES question (id)');
        $this->addSql('ALTER TABLE answer ADD CONSTRAINT FK_DADD4A25F675F31B FOREIGN KEY (author_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE assignment ADD CONSTRAINT FK_30C544BACDF80196 FOREIGN KEY (lesson_id) REFERENCES lesson (id)');
        $this->addSql('ALTER TABLE assignment ADD CONSTRAINT FK_30C544BA654329D5 FOREIGN KEY (rubric_entity_id) REFERENCES rubric (id)');
        $this->addSql('ALTER TABLE assignment_submission ADD CONSTRAINT FK_E5A63E2CD19302F8 FOREIGN KEY (assignment_id) REFERENCES assignment (id)');
        $this->addSql('ALTER TABLE assignment_submission ADD CONSTRAINT FK_E5A63E2CA76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE badge ADD CONSTRAINT FK_FEF0481DC3C8852F FOREIGN KEY (badge_type_id) REFERENCES badge_type (id)');
        $this->addSql('ALTER TABLE badge_user ADD CONSTRAINT FK_299D3A50F7A2C2FC FOREIGN KEY (badge_id) REFERENCES badge (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE badge_user ADD CONSTRAINT FK_299D3A50A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE chat_message ADD CONSTRAINT FK_FAB3FC16F675F31B FOREIGN KEY (author_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE chat_message ADD CONSTRAINT FK_FAB3FC1635983C93 FOREIGN KEY (cohort_id) REFERENCES cohort (id)');
        $this->addSql('ALTER TABLE code_review ADD CONSTRAINT FK_6C5D964E1FD4933 FOREIGN KEY (submission_id) REFERENCES assignment_submission (id)');
        $this->addSql('ALTER TABLE code_review ADD CONSTRAINT FK_6C5D96470574616 FOREIGN KEY (reviewer_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE cohort ADD CONSTRAINT FK_D3B8C16BA40A2C8 FOREIGN KEY (calendar_id) REFERENCES calendar (id)');
        $this->addSql('ALTER TABLE cohort ADD CONSTRAINT FK_D3B8C16B9AC0396 FOREIGN KEY (conversation_id) REFERENCES conversation (id)');
        $this->addSql('ALTER TABLE cohort_course ADD CONSTRAINT FK_A8FE089635983C93 FOREIGN KEY (cohort_id) REFERENCES cohort (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE cohort_course ADD CONSTRAINT FK_A8FE0896591CC992 FOREIGN KEY (course_id) REFERENCES course (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE cohort_challenge ADD CONSTRAINT FK_8316140A35983C93 FOREIGN KEY (cohort_id) REFERENCES cohort (id)');
        $this->addSql('ALTER TABLE collaborative_note ADD CONSTRAINT FK_1A99550035983C93 FOREIGN KEY (cohort_id) REFERENCES cohort (id)');
        $this->addSql('ALTER TABLE comment ADD CONSTRAINT FK_9474526C727ACA70 FOREIGN KEY (parent_id) REFERENCES comment (id)');
        $this->addSql('ALTER TABLE comment ADD CONSTRAINT FK_9474526CA76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE comment ADD CONSTRAINT FK_9474526CEF1A9D84 FOREIGN KEY (notification_id) REFERENCES notification (id)');
        $this->addSql('ALTER TABLE comment ADD CONSTRAINT FK_9474526CCDF80196 FOREIGN KEY (lesson_id) REFERENCES lesson (id)');
        $this->addSql('ALTER TABLE comment_user ADD CONSTRAINT FK_ABA574A5F8697D13 FOREIGN KEY (comment_id) REFERENCES comment (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE comment_user ADD CONSTRAINT FK_ABA574A5A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE completion ADD CONSTRAINT FK_38D6377ECDF80196 FOREIGN KEY (lesson_id) REFERENCES lesson (id)');
        $this->addSql('ALTER TABLE completion ADD CONSTRAINT FK_38D6377EA76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE conversation_user ADD CONSTRAINT FK_5AECB5559AC0396 FOREIGN KEY (conversation_id) REFERENCES conversation (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE conversation_user ADD CONSTRAINT FK_5AECB555A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE course ADD CONSTRAINT FK_169E6FB9F675F31B FOREIGN KEY (author_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE course_user ADD CONSTRAINT FK_45310B4F591CC992 FOREIGN KEY (course_id) REFERENCES course (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE course_user ADD CONSTRAINT FK_45310B4FA76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE course_completion ADD CONSTRAINT FK_E73479FD591CC992 FOREIGN KEY (course_id) REFERENCES course (id)');
        $this->addSql('ALTER TABLE course_completion ADD CONSTRAINT FK_E73479FDA76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE daily_win ADD CONSTRAINT FK_B2F8DD1AA76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE dashboard_widget ADD CONSTRAINT FK_6AC217EBA76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE equity ADD CONSTRAINT FK_5424235EA76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE evaluation ADD CONSTRAINT FK_1323A575A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE evaluation ADD CONSTRAINT FK_1323A57535983C93 FOREIGN KEY (cohort_id) REFERENCES cohort (id)');
        $this->addSql('ALTER TABLE event ADD CONSTRAINT FK_3BAE0AA7C54C8C93 FOREIGN KEY (type_id) REFERENCES event_category (id)');
        $this->addSql('ALTER TABLE event ADD CONSTRAINT FK_3BAE0AA7A40A2C8 FOREIGN KEY (calendar_id) REFERENCES calendar (id)');
        $this->addSql('ALTER TABLE event ADD CONSTRAINT FK_3BAE0AA735983C93 FOREIGN KEY (cohort_id) REFERENCES cohort (id)');
        $this->addSql('ALTER TABLE external_account ADD CONSTRAINT FK_A4948FE7A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE external_learning ADD CONSTRAINT FK_20091631A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE flashcard ADD CONSTRAINT FK_70511A09111948DC FOREIGN KEY (deck_id) REFERENCES flashcard_deck (id)');
        $this->addSql('ALTER TABLE flashcard_deck ADD CONSTRAINT FK_627CAED77E3C61F9 FOREIGN KEY (owner_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE hackathon_user ADD CONSTRAINT FK_58930177996D90CF FOREIGN KEY (hackathon_id) REFERENCES hackathon (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE hackathon_user ADD CONSTRAINT FK_58930177A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE helpful_vote ADD CONSTRAINT FK_59855A3BEBB4B8AD FOREIGN KEY (voter_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE helpful_vote ADD CONSTRAINT FK_59855A3BF8697D13 FOREIGN KEY (comment_id) REFERENCES comment (id)');
        $this->addSql('ALTER TABLE lesson ADD CONSTRAINT FK_F87474F3AFC2B591 FOREIGN KEY (module_id) REFERENCES module (id)');
        $this->addSql('ALTER TABLE lesson ADD CONSTRAINT FK_F87474F3F675F31B FOREIGN KEY (author_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE lesson_tip ADD CONSTRAINT FK_3AF61EAFCDF80196 FOREIGN KEY (lesson_id) REFERENCES lesson (id)');
        $this->addSql('ALTER TABLE lesson_tip ADD CONSTRAINT FK_3AF61EAFF675F31B FOREIGN KEY (author_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE mentorship ADD CONSTRAINT FK_ADE55FF4DB403044 FOREIGN KEY (mentor_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE mentorship ADD CONSTRAINT FK_ADE55FF45C3E47C3 FOREIGN KEY (mentee_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F9AC0396 FOREIGN KEY (conversation_id) REFERENCES conversation (id)');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307FF624B39D FOREIGN KEY (sender_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE mind_map ADD CONSTRAINT FK_912CB0CFAFC2B591 FOREIGN KEY (module_id) REFERENCES module (id)');
        $this->addSql('ALTER TABLE module ADD CONSTRAINT FK_C242628F675F31B FOREIGN KEY (author_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE module_course ADD CONSTRAINT FK_BC9D2F96AFC2B591 FOREIGN KEY (module_id) REFERENCES module (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE module_course ADD CONSTRAINT FK_BC9D2F96591CC992 FOREIGN KEY (course_id) REFERENCES course (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE module_completion ADD CONSTRAINT FK_AD331CE3AFC2B591 FOREIGN KEY (module_id) REFERENCES module (id)');
        $this->addSql('ALTER TABLE module_completion ADD CONSTRAINT FK_AD331CE3A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE note ADD CONSTRAINT FK_CFBDFA14A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE note ADD CONSTRAINT FK_CFBDFA14CDF80196 FOREIGN KEY (lesson_id) REFERENCES lesson (id)');
        $this->addSql('ALTER TABLE note_likes ADD CONSTRAINT FK_2CDAEDAA26ED0855 FOREIGN KEY (note_id) REFERENCES note (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE note_likes ADD CONSTRAINT FK_2CDAEDAAA76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE note_note_tag ADD CONSTRAINT FK_63214BFD26ED0855 FOREIGN KEY (note_id) REFERENCES note (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE note_note_tag ADD CONSTRAINT FK_63214BFDA20034C5 FOREIGN KEY (note_tag_id) REFERENCES note_tag (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAA76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE payout ADD CONSTRAINT FK_4E2EA90261220EA6 FOREIGN KEY (creator_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE payout ADD CONSTRAINT FK_4E2EA902591CC992 FOREIGN KEY (course_id) REFERENCES course (id)');
        $this->addSql('ALTER TABLE peer_resource ADD CONSTRAINT FK_A216EB19F675F31B FOREIGN KEY (author_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE peer_review ADD CONSTRAINT FK_47F6C716E1FD4933 FOREIGN KEY (submission_id) REFERENCES assignment_submission (id)');
        $this->addSql('ALTER TABLE peer_review ADD CONSTRAINT FK_47F6C71670574616 FOREIGN KEY (reviewer_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE peer_review_score ADD CONSTRAINT FK_E0C3DCBE97766307 FOREIGN KEY (criterion_id) REFERENCES rubric_criterion (id)');
        $this->addSql('ALTER TABLE peer_review_score ADD CONSTRAINT FK_E0C3DCBEAE8F0C15 FOREIGN KEY (peer_review_id) REFERENCES peer_review (id)');
        $this->addSql('ALTER TABLE playlist ADD CONSTRAINT FK_D782112D7E3C61F9 FOREIGN KEY (owner_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE playlist_lesson ADD CONSTRAINT FK_170278C06BBD148 FOREIGN KEY (playlist_id) REFERENCES playlist (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE playlist_lesson ADD CONSTRAINT FK_170278C0CDF80196 FOREIGN KEY (lesson_id) REFERENCES lesson (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pomodoro_room ADD CONSTRAINT FK_376385129AC0396 FOREIGN KEY (conversation_id) REFERENCES conversation (id)');
        $this->addSql('ALTER TABLE portfolio_project ADD CONSTRAINT FK_7906FF20A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE proof_of_work ADD CONSTRAINT FK_56543EE7A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE push_subscription ADD CONSTRAINT FK_562830F3A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE question ADD CONSTRAINT FK_B6F7494EF675F31B FOREIGN KEY (author_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE quiz ADD CONSTRAINT FK_A412FA92CDF80196 FOREIGN KEY (lesson_id) REFERENCES lesson (id)');
        $this->addSql('ALTER TABLE quiz ADD CONSTRAINT FK_A412FA92AFC2B591 FOREIGN KEY (module_id) REFERENCES module (id)');
        $this->addSql('ALTER TABLE quiz_option ADD CONSTRAINT FK_B7C2F0E91E27F6BF FOREIGN KEY (question_id) REFERENCES quiz_question (id)');
        $this->addSql('ALTER TABLE quiz_question ADD CONSTRAINT FK_6033B00B853CD175 FOREIGN KEY (quiz_id) REFERENCES quiz (id)');
        $this->addSql('ALTER TABLE raffle_entry ADD CONSTRAINT FK_9F6F1A1CA76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE referral ADD CONSTRAINT FK_73079D00798C22DB FOREIGN KEY (referrer_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE referral ADD CONSTRAINT FK_73079D004A087CA2 FOREIGN KEY (referee_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE reset_password_request ADD CONSTRAINT FK_7CE748AA76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C6F675F31B FOREIGN KEY (author_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C6591CC992 FOREIGN KEY (course_id) REFERENCES course (id)');
        $this->addSql('ALTER TABLE rubric_criterion ADD CONSTRAINT FK_98E476F9A29EC0FC FOREIGN KEY (rubric_id) REFERENCES rubric (id)');
        $this->addSql('ALTER TABLE shared_resource ADD CONSTRAINT FK_E9B50535F675F31B FOREIGN KEY (author_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE skill_user ADD CONSTRAINT FK_CAD24AFB5585C142 FOREIGN KEY (skill_id) REFERENCES skill (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE skill_user ADD CONSTRAINT FK_CAD24AFBA76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE skill_course ADD CONSTRAINT FK_39D43BAD5585C142 FOREIGN KEY (skill_id) REFERENCES skill (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE skill_course ADD CONSTRAINT FK_39D43BAD591CC992 FOREIGN KEY (course_id) REFERENCES course (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE skill_endorsement ADD CONSTRAINT FK_BFA5D76F75BD1D29 FOREIGN KEY (giver_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE skill_endorsement ADD CONSTRAINT FK_BFA5D76FCD53EDB6 FOREIGN KEY (receiver_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE skill_endorsement ADD CONSTRAINT FK_BFA5D76F5585C142 FOREIGN KEY (skill_id) REFERENCES skill (id)');
        $this->addSql('ALTER TABLE skill_node ADD CONSTRAINT FK_C23E74F778B64A2 FOREIGN KEY (tree_id) REFERENCES skill_tree (id)');
        $this->addSql('ALTER TABLE skill_node ADD CONSTRAINT FK_C23E74F7276AF86B FOREIGN KEY (prerequisite_id) REFERENCES skill_node (id)');
        $this->addSql('ALTER TABLE study_buddy_request ADD CONSTRAINT FK_2331E0ADF624B39D FOREIGN KEY (sender_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE study_buddy_request ADD CONSTRAINT FK_2331E0ADE92F8F78 FOREIGN KEY (recipient_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE study_group ADD CONSTRAINT FK_32BA142561220EA6 FOREIGN KEY (creator_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE study_group_user ADD CONSTRAINT FK_2355E9595DDDCCCE FOREIGN KEY (study_group_id) REFERENCES study_group (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE study_group_user ADD CONSTRAINT FK_2355E959A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE study_session_invite ADD CONSTRAINT FK_72595DE4F624B39D FOREIGN KEY (sender_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE subtitle ADD CONSTRAINT FK_518597B1CDF80196 FOREIGN KEY (lesson_id) REFERENCES lesson (id)');
        $this->addSql('ALTER TABLE team ADD CONSTRAINT FK_C4E0A61F7E3C61F9 FOREIGN KEY (owner_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE team ADD CONSTRAINT FK_C4E0A61F35983C93 FOREIGN KEY (cohort_id) REFERENCES cohort (id)');
        $this->addSql('ALTER TABLE team_user ADD CONSTRAINT FK_5C722232296CD8AE FOREIGN KEY (team_id) REFERENCES team (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE team_user ADD CONSTRAINT FK_5C722232A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE topic ADD CONSTRAINT FK_9D40DE1B12469DE2 FOREIGN KEY (category_id) REFERENCES topic_category (id)');
        $this->addSql('ALTER TABLE topic_category ADD CONSTRAINT FK_F07D94C7CF89DA37 FOREIGN KEY (restricted_to_cohort_id) REFERENCES cohort (id)');
        $this->addSql('ALTER TABLE topic_vote ADD CONSTRAINT FK_62FBE4D11F55203D FOREIGN KEY (topic_id) REFERENCES topic (id)');
        $this->addSql('ALTER TABLE topic_vote ADD CONSTRAINT FK_62FBE4D1A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D1A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE `user` ADD CONSTRAINT FK_8D93D649EEBE8D3F FOREIGN KEY (current_cohort_id) REFERENCES cohort (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE `user` ADD CONSTRAINT FK_8D93D649296CD8AE FOREIGN KEY (team_id) REFERENCES team (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE `user` ADD CONSTRAINT FK_8D93D649C52FB298 FOREIGN KEY (active_frame_id) REFERENCES avatar_frame (id)');
        $this->addSql('ALTER TABLE user_cohort ADD CONSTRAINT FK_B6EADA56A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_cohort ADD CONSTRAINT FK_B6EADA5635983C93 FOREIGN KEY (cohort_id) REFERENCES cohort (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_unlocked_bonuses ADD CONSTRAINT FK_9A506AA0A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_unlocked_bonuses ADD CONSTRAINT FK_9A506AA069545666 FOREIGN KEY (bonus_id) REFERENCES bonus (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_unlocked_frames ADD CONSTRAINT FK_414895E9A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_unlocked_frames ADD CONSTRAINT FK_414895E95E1E529B FOREIGN KEY (avatar_frame_id) REFERENCES avatar_frame (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE vip_event ADD CONSTRAINT FK_462882D235983C93 FOREIGN KEY (cohort_id) REFERENCES cohort (id)');
        $this->addSql('ALTER TABLE xp_transaction ADD CONSTRAINT FK_E526D970A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE activity DROP FOREIGN KEY FK_AC74095AA76ED395');
        $this->addSql('ALTER TABLE amaevent DROP FOREIGN KEY FK_AD26732C9A4AA658');
        $this->addSql('ALTER TABLE answer DROP FOREIGN KEY FK_DADD4A251E27F6BF');
        $this->addSql('ALTER TABLE answer DROP FOREIGN KEY FK_DADD4A25F675F31B');
        $this->addSql('ALTER TABLE assignment DROP FOREIGN KEY FK_30C544BACDF80196');
        $this->addSql('ALTER TABLE assignment DROP FOREIGN KEY FK_30C544BA654329D5');
        $this->addSql('ALTER TABLE assignment_submission DROP FOREIGN KEY FK_E5A63E2CD19302F8');
        $this->addSql('ALTER TABLE assignment_submission DROP FOREIGN KEY FK_E5A63E2CA76ED395');
        $this->addSql('ALTER TABLE badge DROP FOREIGN KEY FK_FEF0481DC3C8852F');
        $this->addSql('ALTER TABLE badge_user DROP FOREIGN KEY FK_299D3A50F7A2C2FC');
        $this->addSql('ALTER TABLE badge_user DROP FOREIGN KEY FK_299D3A50A76ED395');
        $this->addSql('ALTER TABLE chat_message DROP FOREIGN KEY FK_FAB3FC16F675F31B');
        $this->addSql('ALTER TABLE chat_message DROP FOREIGN KEY FK_FAB3FC1635983C93');
        $this->addSql('ALTER TABLE code_review DROP FOREIGN KEY FK_6C5D964E1FD4933');
        $this->addSql('ALTER TABLE code_review DROP FOREIGN KEY FK_6C5D96470574616');
        $this->addSql('ALTER TABLE cohort DROP FOREIGN KEY FK_D3B8C16BA40A2C8');
        $this->addSql('ALTER TABLE cohort DROP FOREIGN KEY FK_D3B8C16B9AC0396');
        $this->addSql('ALTER TABLE cohort_course DROP FOREIGN KEY FK_A8FE089635983C93');
        $this->addSql('ALTER TABLE cohort_course DROP FOREIGN KEY FK_A8FE0896591CC992');
        $this->addSql('ALTER TABLE cohort_challenge DROP FOREIGN KEY FK_8316140A35983C93');
        $this->addSql('ALTER TABLE collaborative_note DROP FOREIGN KEY FK_1A99550035983C93');
        $this->addSql('ALTER TABLE comment DROP FOREIGN KEY FK_9474526C727ACA70');
        $this->addSql('ALTER TABLE comment DROP FOREIGN KEY FK_9474526CA76ED395');
        $this->addSql('ALTER TABLE comment DROP FOREIGN KEY FK_9474526CEF1A9D84');
        $this->addSql('ALTER TABLE comment DROP FOREIGN KEY FK_9474526CCDF80196');
        $this->addSql('ALTER TABLE comment_user DROP FOREIGN KEY FK_ABA574A5F8697D13');
        $this->addSql('ALTER TABLE comment_user DROP FOREIGN KEY FK_ABA574A5A76ED395');
        $this->addSql('ALTER TABLE completion DROP FOREIGN KEY FK_38D6377ECDF80196');
        $this->addSql('ALTER TABLE completion DROP FOREIGN KEY FK_38D6377EA76ED395');
        $this->addSql('ALTER TABLE conversation_user DROP FOREIGN KEY FK_5AECB5559AC0396');
        $this->addSql('ALTER TABLE conversation_user DROP FOREIGN KEY FK_5AECB555A76ED395');
        $this->addSql('ALTER TABLE course DROP FOREIGN KEY FK_169E6FB9F675F31B');
        $this->addSql('ALTER TABLE course_user DROP FOREIGN KEY FK_45310B4F591CC992');
        $this->addSql('ALTER TABLE course_user DROP FOREIGN KEY FK_45310B4FA76ED395');
        $this->addSql('ALTER TABLE course_completion DROP FOREIGN KEY FK_E73479FD591CC992');
        $this->addSql('ALTER TABLE course_completion DROP FOREIGN KEY FK_E73479FDA76ED395');
        $this->addSql('ALTER TABLE daily_win DROP FOREIGN KEY FK_B2F8DD1AA76ED395');
        $this->addSql('ALTER TABLE dashboard_widget DROP FOREIGN KEY FK_6AC217EBA76ED395');
        $this->addSql('ALTER TABLE equity DROP FOREIGN KEY FK_5424235EA76ED395');
        $this->addSql('ALTER TABLE evaluation DROP FOREIGN KEY FK_1323A575A76ED395');
        $this->addSql('ALTER TABLE evaluation DROP FOREIGN KEY FK_1323A57535983C93');
        $this->addSql('ALTER TABLE event DROP FOREIGN KEY FK_3BAE0AA7C54C8C93');
        $this->addSql('ALTER TABLE event DROP FOREIGN KEY FK_3BAE0AA7A40A2C8');
        $this->addSql('ALTER TABLE event DROP FOREIGN KEY FK_3BAE0AA735983C93');
        $this->addSql('ALTER TABLE external_account DROP FOREIGN KEY FK_A4948FE7A76ED395');
        $this->addSql('ALTER TABLE external_learning DROP FOREIGN KEY FK_20091631A76ED395');
        $this->addSql('ALTER TABLE flashcard DROP FOREIGN KEY FK_70511A09111948DC');
        $this->addSql('ALTER TABLE flashcard_deck DROP FOREIGN KEY FK_627CAED77E3C61F9');
        $this->addSql('ALTER TABLE hackathon_user DROP FOREIGN KEY FK_58930177996D90CF');
        $this->addSql('ALTER TABLE hackathon_user DROP FOREIGN KEY FK_58930177A76ED395');
        $this->addSql('ALTER TABLE helpful_vote DROP FOREIGN KEY FK_59855A3BEBB4B8AD');
        $this->addSql('ALTER TABLE helpful_vote DROP FOREIGN KEY FK_59855A3BF8697D13');
        $this->addSql('ALTER TABLE lesson DROP FOREIGN KEY FK_F87474F3AFC2B591');
        $this->addSql('ALTER TABLE lesson DROP FOREIGN KEY FK_F87474F3F675F31B');
        $this->addSql('ALTER TABLE lesson_tip DROP FOREIGN KEY FK_3AF61EAFCDF80196');
        $this->addSql('ALTER TABLE lesson_tip DROP FOREIGN KEY FK_3AF61EAFF675F31B');
        $this->addSql('ALTER TABLE mentorship DROP FOREIGN KEY FK_ADE55FF4DB403044');
        $this->addSql('ALTER TABLE mentorship DROP FOREIGN KEY FK_ADE55FF45C3E47C3');
        $this->addSql('ALTER TABLE message DROP FOREIGN KEY FK_B6BD307F9AC0396');
        $this->addSql('ALTER TABLE message DROP FOREIGN KEY FK_B6BD307FF624B39D');
        $this->addSql('ALTER TABLE mind_map DROP FOREIGN KEY FK_912CB0CFAFC2B591');
        $this->addSql('ALTER TABLE module DROP FOREIGN KEY FK_C242628F675F31B');
        $this->addSql('ALTER TABLE module_course DROP FOREIGN KEY FK_BC9D2F96AFC2B591');
        $this->addSql('ALTER TABLE module_course DROP FOREIGN KEY FK_BC9D2F96591CC992');
        $this->addSql('ALTER TABLE module_completion DROP FOREIGN KEY FK_AD331CE3AFC2B591');
        $this->addSql('ALTER TABLE module_completion DROP FOREIGN KEY FK_AD331CE3A76ED395');
        $this->addSql('ALTER TABLE note DROP FOREIGN KEY FK_CFBDFA14A76ED395');
        $this->addSql('ALTER TABLE note DROP FOREIGN KEY FK_CFBDFA14CDF80196');
        $this->addSql('ALTER TABLE note_likes DROP FOREIGN KEY FK_2CDAEDAA26ED0855');
        $this->addSql('ALTER TABLE note_likes DROP FOREIGN KEY FK_2CDAEDAAA76ED395');
        $this->addSql('ALTER TABLE note_note_tag DROP FOREIGN KEY FK_63214BFD26ED0855');
        $this->addSql('ALTER TABLE note_note_tag DROP FOREIGN KEY FK_63214BFDA20034C5');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY FK_BF5476CAA76ED395');
        $this->addSql('ALTER TABLE payout DROP FOREIGN KEY FK_4E2EA90261220EA6');
        $this->addSql('ALTER TABLE payout DROP FOREIGN KEY FK_4E2EA902591CC992');
        $this->addSql('ALTER TABLE peer_resource DROP FOREIGN KEY FK_A216EB19F675F31B');
        $this->addSql('ALTER TABLE peer_review DROP FOREIGN KEY FK_47F6C716E1FD4933');
        $this->addSql('ALTER TABLE peer_review DROP FOREIGN KEY FK_47F6C71670574616');
        $this->addSql('ALTER TABLE peer_review_score DROP FOREIGN KEY FK_E0C3DCBE97766307');
        $this->addSql('ALTER TABLE peer_review_score DROP FOREIGN KEY FK_E0C3DCBEAE8F0C15');
        $this->addSql('ALTER TABLE playlist DROP FOREIGN KEY FK_D782112D7E3C61F9');
        $this->addSql('ALTER TABLE playlist_lesson DROP FOREIGN KEY FK_170278C06BBD148');
        $this->addSql('ALTER TABLE playlist_lesson DROP FOREIGN KEY FK_170278C0CDF80196');
        $this->addSql('ALTER TABLE pomodoro_room DROP FOREIGN KEY FK_376385129AC0396');
        $this->addSql('ALTER TABLE portfolio_project DROP FOREIGN KEY FK_7906FF20A76ED395');
        $this->addSql('ALTER TABLE proof_of_work DROP FOREIGN KEY FK_56543EE7A76ED395');
        $this->addSql('ALTER TABLE push_subscription DROP FOREIGN KEY FK_562830F3A76ED395');
        $this->addSql('ALTER TABLE question DROP FOREIGN KEY FK_B6F7494EF675F31B');
        $this->addSql('ALTER TABLE quiz DROP FOREIGN KEY FK_A412FA92CDF80196');
        $this->addSql('ALTER TABLE quiz DROP FOREIGN KEY FK_A412FA92AFC2B591');
        $this->addSql('ALTER TABLE quiz_option DROP FOREIGN KEY FK_B7C2F0E91E27F6BF');
        $this->addSql('ALTER TABLE quiz_question DROP FOREIGN KEY FK_6033B00B853CD175');
        $this->addSql('ALTER TABLE raffle_entry DROP FOREIGN KEY FK_9F6F1A1CA76ED395');
        $this->addSql('ALTER TABLE referral DROP FOREIGN KEY FK_73079D00798C22DB');
        $this->addSql('ALTER TABLE referral DROP FOREIGN KEY FK_73079D004A087CA2');
        $this->addSql('ALTER TABLE reset_password_request DROP FOREIGN KEY FK_7CE748AA76ED395');
        $this->addSql('ALTER TABLE review DROP FOREIGN KEY FK_794381C6F675F31B');
        $this->addSql('ALTER TABLE review DROP FOREIGN KEY FK_794381C6591CC992');
        $this->addSql('ALTER TABLE rubric_criterion DROP FOREIGN KEY FK_98E476F9A29EC0FC');
        $this->addSql('ALTER TABLE shared_resource DROP FOREIGN KEY FK_E9B50535F675F31B');
        $this->addSql('ALTER TABLE skill_user DROP FOREIGN KEY FK_CAD24AFB5585C142');
        $this->addSql('ALTER TABLE skill_user DROP FOREIGN KEY FK_CAD24AFBA76ED395');
        $this->addSql('ALTER TABLE skill_course DROP FOREIGN KEY FK_39D43BAD5585C142');
        $this->addSql('ALTER TABLE skill_course DROP FOREIGN KEY FK_39D43BAD591CC992');
        $this->addSql('ALTER TABLE skill_endorsement DROP FOREIGN KEY FK_BFA5D76F75BD1D29');
        $this->addSql('ALTER TABLE skill_endorsement DROP FOREIGN KEY FK_BFA5D76FCD53EDB6');
        $this->addSql('ALTER TABLE skill_endorsement DROP FOREIGN KEY FK_BFA5D76F5585C142');
        $this->addSql('ALTER TABLE skill_node DROP FOREIGN KEY FK_C23E74F778B64A2');
        $this->addSql('ALTER TABLE skill_node DROP FOREIGN KEY FK_C23E74F7276AF86B');
        $this->addSql('ALTER TABLE study_buddy_request DROP FOREIGN KEY FK_2331E0ADF624B39D');
        $this->addSql('ALTER TABLE study_buddy_request DROP FOREIGN KEY FK_2331E0ADE92F8F78');
        $this->addSql('ALTER TABLE study_group DROP FOREIGN KEY FK_32BA142561220EA6');
        $this->addSql('ALTER TABLE study_group_user DROP FOREIGN KEY FK_2355E9595DDDCCCE');
        $this->addSql('ALTER TABLE study_group_user DROP FOREIGN KEY FK_2355E959A76ED395');
        $this->addSql('ALTER TABLE study_session_invite DROP FOREIGN KEY FK_72595DE4F624B39D');
        $this->addSql('ALTER TABLE subtitle DROP FOREIGN KEY FK_518597B1CDF80196');
        $this->addSql('ALTER TABLE team DROP FOREIGN KEY FK_C4E0A61F7E3C61F9');
        $this->addSql('ALTER TABLE team DROP FOREIGN KEY FK_C4E0A61F35983C93');
        $this->addSql('ALTER TABLE team_user DROP FOREIGN KEY FK_5C722232296CD8AE');
        $this->addSql('ALTER TABLE team_user DROP FOREIGN KEY FK_5C722232A76ED395');
        $this->addSql('ALTER TABLE topic DROP FOREIGN KEY FK_9D40DE1B12469DE2');
        $this->addSql('ALTER TABLE topic_category DROP FOREIGN KEY FK_F07D94C7CF89DA37');
        $this->addSql('ALTER TABLE topic_vote DROP FOREIGN KEY FK_62FBE4D11F55203D');
        $this->addSql('ALTER TABLE topic_vote DROP FOREIGN KEY FK_62FBE4D1A76ED395');
        $this->addSql('ALTER TABLE transaction DROP FOREIGN KEY FK_723705D1A76ED395');
        $this->addSql('ALTER TABLE `user` DROP FOREIGN KEY FK_8D93D649EEBE8D3F');
        $this->addSql('ALTER TABLE `user` DROP FOREIGN KEY FK_8D93D649296CD8AE');
        $this->addSql('ALTER TABLE `user` DROP FOREIGN KEY FK_8D93D649C52FB298');
        $this->addSql('ALTER TABLE user_cohort DROP FOREIGN KEY FK_B6EADA56A76ED395');
        $this->addSql('ALTER TABLE user_cohort DROP FOREIGN KEY FK_B6EADA5635983C93');
        $this->addSql('ALTER TABLE user_unlocked_bonuses DROP FOREIGN KEY FK_9A506AA0A76ED395');
        $this->addSql('ALTER TABLE user_unlocked_bonuses DROP FOREIGN KEY FK_9A506AA069545666');
        $this->addSql('ALTER TABLE user_unlocked_frames DROP FOREIGN KEY FK_414895E9A76ED395');
        $this->addSql('ALTER TABLE user_unlocked_frames DROP FOREIGN KEY FK_414895E95E1E529B');
        $this->addSql('ALTER TABLE vip_event DROP FOREIGN KEY FK_462882D235983C93');
        $this->addSql('ALTER TABLE xp_transaction DROP FOREIGN KEY FK_E526D970A76ED395');
        $this->addSql('DROP TABLE activity');
        $this->addSql('DROP TABLE amaevent');
        $this->addSql('DROP TABLE answer');
        $this->addSql('DROP TABLE assignment');
        $this->addSql('DROP TABLE assignment_submission');
        $this->addSql('DROP TABLE avatar_frame');
        $this->addSql('DROP TABLE badge');
        $this->addSql('DROP TABLE badge_user');
        $this->addSql('DROP TABLE badge_type');
        $this->addSql('DROP TABLE behind_the_scenes');
        $this->addSql('DROP TABLE bonus');
        $this->addSql('DROP TABLE calendar');
        $this->addSql('DROP TABLE chat_message');
        $this->addSql('DROP TABLE code_review');
        $this->addSql('DROP TABLE cohort');
        $this->addSql('DROP TABLE cohort_course');
        $this->addSql('DROP TABLE cohort_challenge');
        $this->addSql('DROP TABLE collaborative_note');
        $this->addSql('DROP TABLE comment');
        $this->addSql('DROP TABLE comment_user');
        $this->addSql('DROP TABLE completion');
        $this->addSql('DROP TABLE conversation');
        $this->addSql('DROP TABLE conversation_user');
        $this->addSql('DROP TABLE cosmetic');
        $this->addSql('DROP TABLE course');
        $this->addSql('DROP TABLE course_user');
        $this->addSql('DROP TABLE course_completion');
        $this->addSql('DROP TABLE daily_win');
        $this->addSql('DROP TABLE dashboard_widget');
        $this->addSql('DROP TABLE equity');
        $this->addSql('DROP TABLE evaluation');
        $this->addSql('DROP TABLE event');
        $this->addSql('DROP TABLE event_category');
        $this->addSql('DROP TABLE external_account');
        $this->addSql('DROP TABLE external_learning');
        $this->addSql('DROP TABLE flashcard');
        $this->addSql('DROP TABLE flashcard_deck');
        $this->addSql('DROP TABLE glossary_term');
        $this->addSql('DROP TABLE hackathon');
        $this->addSql('DROP TABLE hackathon_user');
        $this->addSql('DROP TABLE helpful_vote');
        $this->addSql('DROP TABLE job_offer');
        $this->addSql('DROP TABLE lesson');
        $this->addSql('DROP TABLE lesson_tip');
        $this->addSql('DROP TABLE mentorship');
        $this->addSql('DROP TABLE message');
        $this->addSql('DROP TABLE mind_map');
        $this->addSql('DROP TABLE module');
        $this->addSql('DROP TABLE module_course');
        $this->addSql('DROP TABLE module_completion');
        $this->addSql('DROP TABLE note');
        $this->addSql('DROP TABLE note_likes');
        $this->addSql('DROP TABLE note_note_tag');
        $this->addSql('DROP TABLE note_tag');
        $this->addSql('DROP TABLE notification');
        $this->addSql('DROP TABLE page');
        $this->addSql('DROP TABLE payment_setting');
        $this->addSql('DROP TABLE payout');
        $this->addSql('DROP TABLE peer_resource');
        $this->addSql('DROP TABLE peer_review');
        $this->addSql('DROP TABLE peer_review_score');
        $this->addSql('DROP TABLE playlist');
        $this->addSql('DROP TABLE playlist_lesson');
        $this->addSql('DROP TABLE pomodoro_room');
        $this->addSql('DROP TABLE portfolio_project');
        $this->addSql('DROP TABLE proof_of_work');
        $this->addSql('DROP TABLE push_subscription');
        $this->addSql('DROP TABLE question');
        $this->addSql('DROP TABLE quiz');
        $this->addSql('DROP TABLE quiz_option');
        $this->addSql('DROP TABLE quiz_question');
        $this->addSql('DROP TABLE raffle_entry');
        $this->addSql('DROP TABLE referral');
        $this->addSql('DROP TABLE reset_password_request');
        $this->addSql('DROP TABLE review');
        $this->addSql('DROP TABLE rubric');
        $this->addSql('DROP TABLE rubric_criterion');
        $this->addSql('DROP TABLE setting');
        $this->addSql('DROP TABLE shared_resource');
        $this->addSql('DROP TABLE site_setting');
        $this->addSql('DROP TABLE skill');
        $this->addSql('DROP TABLE skill_user');
        $this->addSql('DROP TABLE skill_course');
        $this->addSql('DROP TABLE skill_endorsement');
        $this->addSql('DROP TABLE skill_node');
        $this->addSql('DROP TABLE skill_tree');
        $this->addSql('DROP TABLE study_buddy_request');
        $this->addSql('DROP TABLE study_group');
        $this->addSql('DROP TABLE study_group_user');
        $this->addSql('DROP TABLE study_session_invite');
        $this->addSql('DROP TABLE subtitle');
        $this->addSql('DROP TABLE team');
        $this->addSql('DROP TABLE team_user');
        $this->addSql('DROP TABLE theme');
        $this->addSql('DROP TABLE topic');
        $this->addSql('DROP TABLE topic_category');
        $this->addSql('DROP TABLE topic_vote');
        $this->addSql('DROP TABLE transaction');
        $this->addSql('DROP TABLE trivia_question');
        $this->addSql('DROP TABLE `user`');
        $this->addSql('DROP TABLE user_cohort');
        $this->addSql('DROP TABLE user_unlocked_bonuses');
        $this->addSql('DROP TABLE user_unlocked_frames');
        $this->addSql('DROP TABLE vip_event');
        $this->addSql('DROP TABLE xp_transaction');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
