<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260117000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add Social Learning entities (Skills, Portfolio, Assignments, PeerReview, Chat)';
    }

    public function up(Schema $schema): void
    {
        // Skill
        $this->addSql('CREATE TABLE skill (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE skill_user (skill_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY(skill_id, user_id))');
        $this->addSql('CREATE INDEX IDX_436299365585C142 ON skill_user (skill_id)');
        $this->addSql('CREATE INDEX IDX_43629936A76ED395 ON skill_user (user_id)');
        $this->addSql('CREATE TABLE skill_course (skill_id INT NOT NULL, course_id INT NOT NULL, PRIMARY KEY(skill_id, course_id))');
        $this->addSql('CREATE INDEX IDX_7131B3455585C142 ON skill_course (skill_id)');
        $this->addSql('CREATE INDEX IDX_7131B345591CC992 ON skill_course (course_id)');
        $this->addSql('ALTER TABLE skill_user ADD CONSTRAINT FK_436299365585C142 FOREIGN KEY (skill_id) REFERENCES skill (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE skill_user ADD CONSTRAINT FK_43629936A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE skill_course ADD CONSTRAINT FK_7131B3455585C142 FOREIGN KEY (skill_id) REFERENCES skill (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE skill_course ADD CONSTRAINT FK_7131B345591CC992 FOREIGN KEY (course_id) REFERENCES course (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        // PortfolioProject
        $this->addSql('CREATE TABLE portfolio_project (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, url VARCHAR(255) DEFAULT NULL, image VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_372864C6A76ED395 ON portfolio_project (user_id)');
        $this->addSql('ALTER TABLE portfolio_project ADD CONSTRAINT FK_372864C6A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        // Assignment
        $this->addSql('CREATE TABLE assignment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, lesson_id INT NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, rubric JSON DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_30C54483CDF80196 ON assignment (lesson_id)');
        $this->addSql('ALTER TABLE assignment ADD CONSTRAINT FK_30C54483CDF80196 FOREIGN KEY (lesson_id) REFERENCES lesson (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        // AssignmentSubmission
        $this->addSql('CREATE TABLE assignment_submission (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, assignment_id INT NOT NULL, user_id INT NOT NULL, content TEXT NOT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5E90F6D6D19302F8 ON assignment_submission (assignment_id)');
        $this->addSql('CREATE INDEX IDX_5E90F6D6A76ED395 ON assignment_submission (user_id)');
        $this->addSql('COMMENT ON COLUMN assignment_submission.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN assignment_submission.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE assignment_submission ADD CONSTRAINT FK_5E90F6D6D19302F8 FOREIGN KEY (assignment_id) REFERENCES assignment (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE assignment_submission ADD CONSTRAINT FK_5E90F6D6A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        // PeerReview
        $this->addSql('CREATE TABLE peer_review (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, submission_id INT NOT NULL, reviewer_id INT NOT NULL, score SMALLINT NOT NULL, feedback TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_8C148384E1FD4933 ON peer_review (submission_id)');
        $this->addSql('CREATE INDEX IDX_8C14838470574616 ON peer_review (reviewer_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_peer_review ON peer_review (submission_id, reviewer_id)');
        $this->addSql('COMMENT ON COLUMN peer_review.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN peer_review.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE peer_review ADD CONSTRAINT FK_8C148384E1FD4933 FOREIGN KEY (submission_id) REFERENCES assignment_submission (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE peer_review ADD CONSTRAINT FK_8C14838470574616 FOREIGN KEY (reviewer_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        // Chat (Conversation, Message)
        $this->addSql('CREATE TABLE conversation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE conversation_user (conversation_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY(conversation_id, user_id))');
        $this->addSql('CREATE INDEX IDX_5AECB5559AC0396 ON conversation_user (conversation_id)');
        $this->addSql('CREATE INDEX IDX_5AECB555A76ED395 ON conversation_user (user_id)');
        $this->addSql('ALTER TABLE conversation_user ADD CONSTRAINT FK_5AECB5559AC0396 FOREIGN KEY (conversation_id) REFERENCES conversation (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE conversation_user ADD CONSTRAINT FK_5AECB555A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE message (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, conversation_id INT NOT NULL, sender_id INT NOT NULL, content TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_B6BD307F9AC0396 ON message (conversation_id)');
        $this->addSql('CREATE INDEX IDX_B6BD307FF624B39D ON message (sender_id)');
        $this->addSql('COMMENT ON COLUMN message.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN message.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F9AC0396 FOREIGN KEY (conversation_id) REFERENCES conversation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307FF624B39D FOREIGN KEY (sender_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        // Cohort update
        $this->addSql('ALTER TABLE cohort ADD conversation_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE cohort ADD CONSTRAINT FK_909689889AC0396 FOREIGN KEY (conversation_id) REFERENCES conversation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_909689889AC0396 ON cohort (conversation_id)');

        // User update
        $this->addSql('ALTER TABLE "user" ADD timezone VARCHAR(50) DEFAULT \'UTC\' NOT NULL');
        $this->addSql('CREATE INDEX IDX_USER_XP ON "user" (xp)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE skill_user DROP CONSTRAINT FK_436299365585C142');
        $this->addSql('ALTER TABLE skill_user DROP CONSTRAINT FK_43629936A76ED395');
        $this->addSql('ALTER TABLE skill_course DROP CONSTRAINT FK_7131B3455585C142');
        $this->addSql('ALTER TABLE skill_course DROP CONSTRAINT FK_7131B345591CC992');
        $this->addSql('ALTER TABLE portfolio_project DROP CONSTRAINT FK_372864C6A76ED395');
        $this->addSql('ALTER TABLE assignment DROP CONSTRAINT FK_30C54483CDF80196');
        $this->addSql('ALTER TABLE assignment_submission DROP CONSTRAINT FK_5E90F6D6D19302F8');
        $this->addSql('ALTER TABLE assignment_submission DROP CONSTRAINT FK_5E90F6D6A76ED395');
        $this->addSql('ALTER TABLE peer_review DROP CONSTRAINT FK_8C148384E1FD4933');
        $this->addSql('ALTER TABLE peer_review DROP CONSTRAINT FK_8C14838470574616');
        $this->addSql('ALTER TABLE conversation_user DROP CONSTRAINT FK_5AECB5559AC0396');
        $this->addSql('ALTER TABLE conversation_user DROP CONSTRAINT FK_5AECB555A76ED395');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307F9AC0396');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307FF624B39D');
        $this->addSql('ALTER TABLE cohort DROP CONSTRAINT FK_909689889AC0396');

        $this->addSql('DROP TABLE skill');
        $this->addSql('DROP TABLE skill_user');
        $this->addSql('DROP TABLE skill_course');
        $this->addSql('DROP TABLE portfolio_project');
        $this->addSql('DROP TABLE assignment');
        $this->addSql('DROP TABLE assignment_submission');
        $this->addSql('DROP TABLE peer_review');
        $this->addSql('DROP TABLE conversation');
        $this->addSql('DROP TABLE conversation_user');
        $this->addSql('DROP TABLE message');

        $this->addSql('ALTER TABLE cohort DROP conversation_id');

        $this->addSql('DROP INDEX IDX_USER_XP');
        $this->addSql('ALTER TABLE "user" DROP timezone');
    }
}
