<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260317200058 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE activity (id INT AUTO_INCREMENT NOT NULL, action VARCHAR(255) NOT NULL, target_name VARCHAR(255) DEFAULT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at DATETIME DEFAULT NULL, user_id INT NOT NULL, INDEX IDX_AC74095AA76ED395 (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE amaevent (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, date DATETIME NOT NULL, guest_id INT NOT NULL, INDEX IDX_AD26732C9A4AA658 (guest_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE answer (id INT AUTO_INCREMENT NOT NULL, content LONGTEXT NOT NULL, votes INT NOT NULL, question_id INT NOT NULL, author_id INT NOT NULL, INDEX IDX_DADD4A251E27F6BF (question_id), INDEX IDX_DADD4A25F675F31B (author_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE behind_the_scenes (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, content LONGTEXT NOT NULL, min_xp_required INT NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE code_review (id INT AUTO_INCREMENT NOT NULL, comment LONGTEXT NOT NULL, rating INT NOT NULL, submission_id INT NOT NULL, reviewer_id INT NOT NULL, INDEX IDX_6C5D964E1FD4933 (submission_id), INDEX IDX_6C5D96470574616 (reviewer_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE cohort_challenge (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, target_value INT NOT NULL, start_date DATETIME NOT NULL, end_date DATETIME NOT NULL, cohort_id INT NOT NULL, INDEX IDX_8316140A35983C93 (cohort_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE collaborative_note (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, url VARCHAR(255) NOT NULL, cohort_id INT NOT NULL, INDEX IDX_1A99550035983C93 (cohort_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE cosmetic (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(50) NOT NULL, price INT NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE daily_win (id INT AUTO_INCREMENT NOT NULL, summary LONGTEXT NOT NULL, date DATETIME NOT NULL, user_id INT NOT NULL, INDEX IDX_B2F8DD1AA76ED395 (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE dashboard_widget (id INT AUTO_INCREMENT NOT NULL, type VARCHAR(50) NOT NULL, position INT NOT NULL, user_id INT NOT NULL, INDEX IDX_6AC217EBA76ED395 (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE equity (id INT AUTO_INCREMENT NOT NULL, points INT NOT NULL, reason VARCHAR(255) DEFAULT NULL, user_id INT NOT NULL, INDEX IDX_5424235EA76ED395 (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE external_account (id INT AUTO_INCREMENT NOT NULL, platform VARCHAR(50) NOT NULL, account_id VARCHAR(255) NOT NULL, user_id INT NOT NULL, INDEX IDX_A4948FE7A76ED395 (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE external_learning (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, type VARCHAR(50) NOT NULL, status VARCHAR(50) NOT NULL, user_id INT NOT NULL, INDEX IDX_20091631A76ED395 (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE flashcard (id INT AUTO_INCREMENT NOT NULL, question LONGTEXT NOT NULL, answer LONGTEXT NOT NULL, deck_id INT NOT NULL, INDEX IDX_70511A09111948DC (deck_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE flashcard_deck (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, owner_id INT NOT NULL, INDEX IDX_627CAED77E3C61F9 (owner_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE glossary_term (id INT AUTO_INCREMENT NOT NULL, term VARCHAR(255) NOT NULL, definition LONGTEXT NOT NULL, is_approved TINYINT DEFAULT 0 NOT NULL, UNIQUE INDEX UNIQ_334345DDA50FE78D (term), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE hackathon (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, start_date DATETIME NOT NULL, end_date DATETIME NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE hackathon_user (hackathon_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_58930177996D90CF (hackathon_id), INDEX IDX_58930177A76ED395 (user_id), PRIMARY KEY (hackathon_id, user_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE helpful_vote (id INT AUTO_INCREMENT NOT NULL, voter_id INT NOT NULL, comment_id INT NOT NULL, INDEX IDX_59855A3BEBB4B8AD (voter_id), INDEX IDX_59855A3BF8697D13 (comment_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE job_offer (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, company VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, url VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE lesson_tip (id INT AUTO_INCREMENT NOT NULL, content LONGTEXT NOT NULL, lesson_id INT NOT NULL, author_id INT NOT NULL, INDEX IDX_3AF61EAFCDF80196 (lesson_id), INDEX IDX_3AF61EAFF675F31B (author_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE mentorship (id INT AUTO_INCREMENT NOT NULL, status VARCHAR(50) NOT NULL, mentor_id INT NOT NULL, mentee_id INT NOT NULL, INDEX IDX_ADE55FF4DB403044 (mentor_id), INDEX IDX_ADE55FF45C3E47C3 (mentee_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE mind_map (id INT AUTO_INCREMENT NOT NULL, data JSON NOT NULL, module_id INT NOT NULL, UNIQUE INDEX UNIQ_912CB0CFAFC2B591 (module_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE note_note_tag (note_id INT NOT NULL, note_tag_id INT NOT NULL, INDEX IDX_63214BFD26ED0855 (note_id), INDEX IDX_63214BFDA20034C5 (note_tag_id), PRIMARY KEY (note_id, note_tag_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE note_tag (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(50) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE peer_resource (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, url VARCHAR(255) NOT NULL, status VARCHAR(20) NOT NULL, author_id INT NOT NULL, INDEX IDX_A216EB19F675F31B (author_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE playlist (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, owner_id INT NOT NULL, INDEX IDX_D782112D7E3C61F9 (owner_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE playlist_lesson (playlist_id INT NOT NULL, lesson_id INT NOT NULL, INDEX IDX_170278C06BBD148 (playlist_id), INDEX IDX_170278C0CDF80196 (lesson_id), PRIMARY KEY (playlist_id, lesson_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE pomodoro_room (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, conversation_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_376385129AC0396 (conversation_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE proof_of_work (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, link VARCHAR(255) NOT NULL, verification_hash VARCHAR(64) NOT NULL, user_id INT NOT NULL, UNIQUE INDEX UNIQ_56543EE74E8C91BF (verification_hash), INDEX IDX_56543EE7A76ED395 (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE question (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, content LONGTEXT NOT NULL, author_id INT NOT NULL, INDEX IDX_B6F7494EF675F31B (author_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE raffle_entry (id INT AUTO_INCREMENT NOT NULL, raffle_date DATETIME NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at DATETIME DEFAULT NULL, user_id INT NOT NULL, INDEX IDX_9F6F1A1CA76ED395 (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE referral (id INT AUTO_INCREMENT NOT NULL, is_completed TINYINT DEFAULT 0 NOT NULL, referrer_id INT NOT NULL, referee_id INT NOT NULL, INDEX IDX_73079D00798C22DB (referrer_id), UNIQUE INDEX UNIQ_73079D004A087CA2 (referee_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE review (id INT AUTO_INCREMENT NOT NULL, comment LONGTEXT NOT NULL, rating SMALLINT NOT NULL, author_id INT NOT NULL, course_id INT NOT NULL, INDEX IDX_794381C6F675F31B (author_id), INDEX IDX_794381C6591CC992 (course_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE shared_resource (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, url VARCHAR(255) NOT NULL, author_id INT NOT NULL, INDEX IDX_E9B50535F675F31B (author_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE skill_endorsement (id INT AUTO_INCREMENT NOT NULL, giver_id INT NOT NULL, receiver_id INT NOT NULL, skill_id INT NOT NULL, INDEX IDX_BFA5D76F75BD1D29 (giver_id), INDEX IDX_BFA5D76FCD53EDB6 (receiver_id), INDEX IDX_BFA5D76F5585C142 (skill_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE skill_node (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, xp_required INT NOT NULL, tree_id INT NOT NULL, prerequisite_id INT DEFAULT NULL, INDEX IDX_C23E74F778B64A2 (tree_id), INDEX IDX_C23E74F7276AF86B (prerequisite_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE skill_tree (id INT AUTO_INCREMENT NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE study_buddy_request (id INT AUTO_INCREMENT NOT NULL, status VARCHAR(20) NOT NULL, sender_id INT NOT NULL, recipient_id INT NOT NULL, INDEX IDX_2331E0ADF624B39D (sender_id), INDEX IDX_2331E0ADE92F8F78 (recipient_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE study_group (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, topic VARCHAR(255) NOT NULL, max_members INT DEFAULT 10 NOT NULL, creator_id INT NOT NULL, INDEX IDX_32BA142561220EA6 (creator_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE study_group_user (study_group_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_2355E9595DDDCCCE (study_group_id), INDEX IDX_2355E959A76ED395 (user_id), PRIMARY KEY (study_group_id, user_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE study_session_invite (id INT AUTO_INCREMENT NOT NULL, invite_token VARCHAR(64) NOT NULL, is_accepted TINYINT DEFAULT 0 NOT NULL, sender_id INT NOT NULL, UNIQUE INDEX UNIQ_72595DE45242FFC4 (invite_token), INDEX IDX_72595DE4F624B39D (sender_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE subtitle (id INT AUTO_INCREMENT NOT NULL, language VARCHAR(5) NOT NULL, content LONGTEXT NOT NULL, lesson_id INT NOT NULL, INDEX IDX_518597B1CDF80196 (lesson_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE theme (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_9775E70877153098 (code), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE topic (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, category_id INT DEFAULT NULL, INDEX IDX_9D40DE1B12469DE2 (category_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE topic_category (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, restricted_to_cohort_id INT DEFAULT NULL, INDEX IDX_F07D94C7CF89DA37 (restricted_to_cohort_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE topic_vote (id INT AUTO_INCREMENT NOT NULL, topic_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_62FBE4D11F55203D (topic_id), INDEX IDX_62FBE4D1A76ED395 (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE trivia_question (id INT AUTO_INCREMENT NOT NULL, question LONGTEXT NOT NULL, options JSON NOT NULL, correct_answer VARCHAR(1) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE vip_event (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, date DATETIME NOT NULL, min_rank INT NOT NULL, cohort_id INT NOT NULL, INDEX IDX_462882D235983C93 (cohort_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE activity ADD CONSTRAINT FK_AC74095AA76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE amaevent ADD CONSTRAINT FK_AD26732C9A4AA658 FOREIGN KEY (guest_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE answer ADD CONSTRAINT FK_DADD4A251E27F6BF FOREIGN KEY (question_id) REFERENCES question (id)');
        $this->addSql('ALTER TABLE answer ADD CONSTRAINT FK_DADD4A25F675F31B FOREIGN KEY (author_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE code_review ADD CONSTRAINT FK_6C5D964E1FD4933 FOREIGN KEY (submission_id) REFERENCES assignment_submission (id)');
        $this->addSql('ALTER TABLE code_review ADD CONSTRAINT FK_6C5D96470574616 FOREIGN KEY (reviewer_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE cohort_challenge ADD CONSTRAINT FK_8316140A35983C93 FOREIGN KEY (cohort_id) REFERENCES cohort (id)');
        $this->addSql('ALTER TABLE collaborative_note ADD CONSTRAINT FK_1A99550035983C93 FOREIGN KEY (cohort_id) REFERENCES cohort (id)');
        $this->addSql('ALTER TABLE daily_win ADD CONSTRAINT FK_B2F8DD1AA76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE dashboard_widget ADD CONSTRAINT FK_6AC217EBA76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE equity ADD CONSTRAINT FK_5424235EA76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE external_account ADD CONSTRAINT FK_A4948FE7A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE external_learning ADD CONSTRAINT FK_20091631A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE flashcard ADD CONSTRAINT FK_70511A09111948DC FOREIGN KEY (deck_id) REFERENCES flashcard_deck (id)');
        $this->addSql('ALTER TABLE flashcard_deck ADD CONSTRAINT FK_627CAED77E3C61F9 FOREIGN KEY (owner_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE hackathon_user ADD CONSTRAINT FK_58930177996D90CF FOREIGN KEY (hackathon_id) REFERENCES hackathon (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE hackathon_user ADD CONSTRAINT FK_58930177A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE helpful_vote ADD CONSTRAINT FK_59855A3BEBB4B8AD FOREIGN KEY (voter_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE helpful_vote ADD CONSTRAINT FK_59855A3BF8697D13 FOREIGN KEY (comment_id) REFERENCES comment (id)');
        $this->addSql('ALTER TABLE lesson_tip ADD CONSTRAINT FK_3AF61EAFCDF80196 FOREIGN KEY (lesson_id) REFERENCES lesson (id)');
        $this->addSql('ALTER TABLE lesson_tip ADD CONSTRAINT FK_3AF61EAFF675F31B FOREIGN KEY (author_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE mentorship ADD CONSTRAINT FK_ADE55FF4DB403044 FOREIGN KEY (mentor_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE mentorship ADD CONSTRAINT FK_ADE55FF45C3E47C3 FOREIGN KEY (mentee_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE mind_map ADD CONSTRAINT FK_912CB0CFAFC2B591 FOREIGN KEY (module_id) REFERENCES module (id)');
        $this->addSql('ALTER TABLE note_note_tag ADD CONSTRAINT FK_63214BFD26ED0855 FOREIGN KEY (note_id) REFERENCES note (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE note_note_tag ADD CONSTRAINT FK_63214BFDA20034C5 FOREIGN KEY (note_tag_id) REFERENCES note_tag (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE peer_resource ADD CONSTRAINT FK_A216EB19F675F31B FOREIGN KEY (author_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE playlist ADD CONSTRAINT FK_D782112D7E3C61F9 FOREIGN KEY (owner_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE playlist_lesson ADD CONSTRAINT FK_170278C06BBD148 FOREIGN KEY (playlist_id) REFERENCES playlist (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE playlist_lesson ADD CONSTRAINT FK_170278C0CDF80196 FOREIGN KEY (lesson_id) REFERENCES lesson (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pomodoro_room ADD CONSTRAINT FK_376385129AC0396 FOREIGN KEY (conversation_id) REFERENCES conversation (id)');
        $this->addSql('ALTER TABLE proof_of_work ADD CONSTRAINT FK_56543EE7A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE question ADD CONSTRAINT FK_B6F7494EF675F31B FOREIGN KEY (author_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE raffle_entry ADD CONSTRAINT FK_9F6F1A1CA76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE referral ADD CONSTRAINT FK_73079D00798C22DB FOREIGN KEY (referrer_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE referral ADD CONSTRAINT FK_73079D004A087CA2 FOREIGN KEY (referee_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C6F675F31B FOREIGN KEY (author_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C6591CC992 FOREIGN KEY (course_id) REFERENCES course (id)');
        $this->addSql('ALTER TABLE shared_resource ADD CONSTRAINT FK_E9B50535F675F31B FOREIGN KEY (author_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE skill_endorsement ADD CONSTRAINT FK_BFA5D76F75BD1D29 FOREIGN KEY (giver_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE skill_endorsement ADD CONSTRAINT FK_BFA5D76FCD53EDB6 FOREIGN KEY (receiver_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE skill_endorsement ADD CONSTRAINT FK_BFA5D76F5585C142 FOREIGN KEY (skill_id) REFERENCES skill (id)');
        $this->addSql('ALTER TABLE skill_node ADD CONSTRAINT FK_C23E74F778B64A2 FOREIGN KEY (tree_id) REFERENCES skill_tree (id)');
        $this->addSql('ALTER TABLE skill_node ADD CONSTRAINT FK_C23E74F7276AF86B FOREIGN KEY (prerequisite_id) REFERENCES skill_node (id)');
        $this->addSql('ALTER TABLE study_buddy_request ADD CONSTRAINT FK_2331E0ADF624B39D FOREIGN KEY (sender_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE study_buddy_request ADD CONSTRAINT FK_2331E0ADE92F8F78 FOREIGN KEY (recipient_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE study_group ADD CONSTRAINT FK_32BA142561220EA6 FOREIGN KEY (creator_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE study_group_user ADD CONSTRAINT FK_2355E9595DDDCCCE FOREIGN KEY (study_group_id) REFERENCES study_group (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE study_group_user ADD CONSTRAINT FK_2355E959A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE study_session_invite ADD CONSTRAINT FK_72595DE4F624B39D FOREIGN KEY (sender_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE subtitle ADD CONSTRAINT FK_518597B1CDF80196 FOREIGN KEY (lesson_id) REFERENCES lesson (id)');
        $this->addSql('ALTER TABLE topic ADD CONSTRAINT FK_9D40DE1B12469DE2 FOREIGN KEY (category_id) REFERENCES topic_category (id)');
        $this->addSql('ALTER TABLE topic_category ADD CONSTRAINT FK_F07D94C7CF89DA37 FOREIGN KEY (restricted_to_cohort_id) REFERENCES cohort (id)');
        $this->addSql('ALTER TABLE topic_vote ADD CONSTRAINT FK_62FBE4D11F55203D FOREIGN KEY (topic_id) REFERENCES topic (id)');
        $this->addSql('ALTER TABLE topic_vote ADD CONSTRAINT FK_62FBE4D1A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE vip_event ADD CONSTRAINT FK_462882D235983C93 FOREIGN KEY (cohort_id) REFERENCES cohort (id)');
        $this->addSql('DROP INDEX UNIQ_A46B93FA772E836A ON avatar_frame');
        $this->addSql('ALTER TABLE avatar_frame ADD image_path VARCHAR(255) NOT NULL, ADD level_required INT DEFAULT 0 NOT NULL, DROP identifier, DROP css_class, DROP created_at, DROP updated_at');
        $this->addSql('ALTER TABLE cohort ADD is_vip TINYINT DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE comment ADD timestamp INT DEFAULT NULL');
        $this->addSql('ALTER TABLE conversation ADD is_private TINYINT DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE course_completion ADD certificate_type VARCHAR(20) DEFAULT \'simple\' NOT NULL');
        $this->addSql('ALTER TABLE portfolio_project ADD link VARCHAR(255) DEFAULT NULL, DROP url, DROP image');
        $this->addSql('ALTER TABLE team ADD company VARCHAR(255) NOT NULL, ADD completed_lessons INT DEFAULT 0 NOT NULL, ADD cohort_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE team ADD CONSTRAINT FK_C4E0A61F35983C93 FOREIGN KEY (cohort_id) REFERENCES cohort (id)');
        $this->addSql('CREATE INDEX IDX_C4E0A61F35983C93 ON team (cohort_id)');
        $this->addSql('DROP INDEX UNIQ_8D93D649594766AF ON user');
        $this->addSql('ALTER TABLE user ADD learning_manifesto LONGTEXT DEFAULT NULL, ADD weekly_goal_hours INT DEFAULT 0 NOT NULL, ADD is_bootcamp_mode TINYINT DEFAULT 0 NOT NULL, ADD is_alumni TINYINT DEFAULT 0 NOT NULL, ADD quiz_combo INT DEFAULT 0 NOT NULL, ADD rocher_coins INT DEFAULT 0 NOT NULL, DROP login_token, DROP login_token_expires_at, CHANGE google_id cover_photo VARCHAR(255) DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE activity DROP FOREIGN KEY FK_AC74095AA76ED395');
        $this->addSql('ALTER TABLE amaevent DROP FOREIGN KEY FK_AD26732C9A4AA658');
        $this->addSql('ALTER TABLE answer DROP FOREIGN KEY FK_DADD4A251E27F6BF');
        $this->addSql('ALTER TABLE answer DROP FOREIGN KEY FK_DADD4A25F675F31B');
        $this->addSql('ALTER TABLE code_review DROP FOREIGN KEY FK_6C5D964E1FD4933');
        $this->addSql('ALTER TABLE code_review DROP FOREIGN KEY FK_6C5D96470574616');
        $this->addSql('ALTER TABLE cohort_challenge DROP FOREIGN KEY FK_8316140A35983C93');
        $this->addSql('ALTER TABLE collaborative_note DROP FOREIGN KEY FK_1A99550035983C93');
        $this->addSql('ALTER TABLE daily_win DROP FOREIGN KEY FK_B2F8DD1AA76ED395');
        $this->addSql('ALTER TABLE dashboard_widget DROP FOREIGN KEY FK_6AC217EBA76ED395');
        $this->addSql('ALTER TABLE equity DROP FOREIGN KEY FK_5424235EA76ED395');
        $this->addSql('ALTER TABLE external_account DROP FOREIGN KEY FK_A4948FE7A76ED395');
        $this->addSql('ALTER TABLE external_learning DROP FOREIGN KEY FK_20091631A76ED395');
        $this->addSql('ALTER TABLE flashcard DROP FOREIGN KEY FK_70511A09111948DC');
        $this->addSql('ALTER TABLE flashcard_deck DROP FOREIGN KEY FK_627CAED77E3C61F9');
        $this->addSql('ALTER TABLE hackathon_user DROP FOREIGN KEY FK_58930177996D90CF');
        $this->addSql('ALTER TABLE hackathon_user DROP FOREIGN KEY FK_58930177A76ED395');
        $this->addSql('ALTER TABLE helpful_vote DROP FOREIGN KEY FK_59855A3BEBB4B8AD');
        $this->addSql('ALTER TABLE helpful_vote DROP FOREIGN KEY FK_59855A3BF8697D13');
        $this->addSql('ALTER TABLE lesson_tip DROP FOREIGN KEY FK_3AF61EAFCDF80196');
        $this->addSql('ALTER TABLE lesson_tip DROP FOREIGN KEY FK_3AF61EAFF675F31B');
        $this->addSql('ALTER TABLE mentorship DROP FOREIGN KEY FK_ADE55FF4DB403044');
        $this->addSql('ALTER TABLE mentorship DROP FOREIGN KEY FK_ADE55FF45C3E47C3');
        $this->addSql('ALTER TABLE mind_map DROP FOREIGN KEY FK_912CB0CFAFC2B591');
        $this->addSql('ALTER TABLE note_note_tag DROP FOREIGN KEY FK_63214BFD26ED0855');
        $this->addSql('ALTER TABLE note_note_tag DROP FOREIGN KEY FK_63214BFDA20034C5');
        $this->addSql('ALTER TABLE peer_resource DROP FOREIGN KEY FK_A216EB19F675F31B');
        $this->addSql('ALTER TABLE playlist DROP FOREIGN KEY FK_D782112D7E3C61F9');
        $this->addSql('ALTER TABLE playlist_lesson DROP FOREIGN KEY FK_170278C06BBD148');
        $this->addSql('ALTER TABLE playlist_lesson DROP FOREIGN KEY FK_170278C0CDF80196');
        $this->addSql('ALTER TABLE pomodoro_room DROP FOREIGN KEY FK_376385129AC0396');
        $this->addSql('ALTER TABLE proof_of_work DROP FOREIGN KEY FK_56543EE7A76ED395');
        $this->addSql('ALTER TABLE question DROP FOREIGN KEY FK_B6F7494EF675F31B');
        $this->addSql('ALTER TABLE raffle_entry DROP FOREIGN KEY FK_9F6F1A1CA76ED395');
        $this->addSql('ALTER TABLE referral DROP FOREIGN KEY FK_73079D00798C22DB');
        $this->addSql('ALTER TABLE referral DROP FOREIGN KEY FK_73079D004A087CA2');
        $this->addSql('ALTER TABLE review DROP FOREIGN KEY FK_794381C6F675F31B');
        $this->addSql('ALTER TABLE review DROP FOREIGN KEY FK_794381C6591CC992');
        $this->addSql('ALTER TABLE shared_resource DROP FOREIGN KEY FK_E9B50535F675F31B');
        $this->addSql('ALTER TABLE skill_endorsement DROP FOREIGN KEY FK_BFA5D76F75BD1D29');
        $this->addSql('ALTER TABLE skill_endorsement DROP FOREIGN KEY FK_BFA5D76FCD53EDB6');
        $this->addSql('ALTER TABLE skill_endorsement DROP FOREIGN KEY FK_BFA5D76F5585C142');
        $this->addSql('ALTER TABLE skill_node DROP FOREIGN KEY FK_C23E74F778B64A2');
        $this->addSql('ALTER TABLE skill_node DROP FOREIGN KEY FK_C23E74F7276AF86B');
        $this->addSql('ALTER TABLE study_buddy_request DROP FOREIGN KEY FK_2331E0ADF624B39D');
        $this->addSql('ALTER TABLE study_buddy_request DROP FOREIGN KEY FK_2331E0ADE92F8F78');
        $this->addSql('ALTER TABLE study_group DROP FOREIGN KEY FK_32BA142561220EA6');
        $this->addSql('ALTER TABLE study_group_user DROP FOREIGN KEY FK_2355E9595DDDCCCE');
        $this->addSql('ALTER TABLE study_group_user DROP FOREIGN KEY FK_2355E959A76ED395');
        $this->addSql('ALTER TABLE study_session_invite DROP FOREIGN KEY FK_72595DE4F624B39D');
        $this->addSql('ALTER TABLE subtitle DROP FOREIGN KEY FK_518597B1CDF80196');
        $this->addSql('ALTER TABLE topic DROP FOREIGN KEY FK_9D40DE1B12469DE2');
        $this->addSql('ALTER TABLE topic_category DROP FOREIGN KEY FK_F07D94C7CF89DA37');
        $this->addSql('ALTER TABLE topic_vote DROP FOREIGN KEY FK_62FBE4D11F55203D');
        $this->addSql('ALTER TABLE topic_vote DROP FOREIGN KEY FK_62FBE4D1A76ED395');
        $this->addSql('ALTER TABLE vip_event DROP FOREIGN KEY FK_462882D235983C93');
        $this->addSql('DROP TABLE activity');
        $this->addSql('DROP TABLE amaevent');
        $this->addSql('DROP TABLE answer');
        $this->addSql('DROP TABLE behind_the_scenes');
        $this->addSql('DROP TABLE code_review');
        $this->addSql('DROP TABLE cohort_challenge');
        $this->addSql('DROP TABLE collaborative_note');
        $this->addSql('DROP TABLE cosmetic');
        $this->addSql('DROP TABLE daily_win');
        $this->addSql('DROP TABLE dashboard_widget');
        $this->addSql('DROP TABLE equity');
        $this->addSql('DROP TABLE external_account');
        $this->addSql('DROP TABLE external_learning');
        $this->addSql('DROP TABLE flashcard');
        $this->addSql('DROP TABLE flashcard_deck');
        $this->addSql('DROP TABLE glossary_term');
        $this->addSql('DROP TABLE hackathon');
        $this->addSql('DROP TABLE hackathon_user');
        $this->addSql('DROP TABLE helpful_vote');
        $this->addSql('DROP TABLE job_offer');
        $this->addSql('DROP TABLE lesson_tip');
        $this->addSql('DROP TABLE mentorship');
        $this->addSql('DROP TABLE mind_map');
        $this->addSql('DROP TABLE note_note_tag');
        $this->addSql('DROP TABLE note_tag');
        $this->addSql('DROP TABLE peer_resource');
        $this->addSql('DROP TABLE playlist');
        $this->addSql('DROP TABLE playlist_lesson');
        $this->addSql('DROP TABLE pomodoro_room');
        $this->addSql('DROP TABLE proof_of_work');
        $this->addSql('DROP TABLE question');
        $this->addSql('DROP TABLE raffle_entry');
        $this->addSql('DROP TABLE referral');
        $this->addSql('DROP TABLE review');
        $this->addSql('DROP TABLE shared_resource');
        $this->addSql('DROP TABLE skill_endorsement');
        $this->addSql('DROP TABLE skill_node');
        $this->addSql('DROP TABLE skill_tree');
        $this->addSql('DROP TABLE study_buddy_request');
        $this->addSql('DROP TABLE study_group');
        $this->addSql('DROP TABLE study_group_user');
        $this->addSql('DROP TABLE study_session_invite');
        $this->addSql('DROP TABLE subtitle');
        $this->addSql('DROP TABLE theme');
        $this->addSql('DROP TABLE topic');
        $this->addSql('DROP TABLE topic_category');
        $this->addSql('DROP TABLE topic_vote');
        $this->addSql('DROP TABLE trivia_question');
        $this->addSql('DROP TABLE vip_event');
        $this->addSql('ALTER TABLE avatar_frame ADD css_class VARCHAR(255) NOT NULL, ADD created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, ADD updated_at DATETIME DEFAULT NULL, DROP level_required, CHANGE image_path identifier VARCHAR(255) NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A46B93FA772E836A ON avatar_frame (identifier)');
        $this->addSql('ALTER TABLE cohort DROP is_vip');
        $this->addSql('ALTER TABLE comment DROP timestamp');
        $this->addSql('ALTER TABLE conversation DROP is_private');
        $this->addSql('ALTER TABLE course_completion DROP certificate_type');
        $this->addSql('ALTER TABLE portfolio_project ADD image VARCHAR(255) DEFAULT NULL, CHANGE link url VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE team DROP FOREIGN KEY FK_C4E0A61F35983C93');
        $this->addSql('DROP INDEX IDX_C4E0A61F35983C93 ON team');
        $this->addSql('ALTER TABLE team DROP company, DROP completed_lessons, DROP cohort_id');
        $this->addSql('ALTER TABLE `user` ADD login_token VARCHAR(128) DEFAULT NULL, ADD login_token_expires_at DATETIME DEFAULT NULL, DROP learning_manifesto, DROP weekly_goal_hours, DROP is_bootcamp_mode, DROP is_alumni, DROP quiz_combo, DROP rocher_coins, CHANGE cover_photo google_id VARCHAR(255) DEFAULT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649594766AF ON `user` (login_token)');
    }
}
